import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";
import men1 from "../assets/images/menPerfume/men1.jpg";
import men2 from "../assets/images/menPerfume/men2.jpg";
import men3 from "../assets/images/menPerfume/men3.jpg";
import men4 from "../assets/images/menPerfume/men4.jpg";
import men5 from "../assets/images/menPerfume/men5.jpg";
import men6 from "../assets/images/menPerfume/men6.jpg";
import men7 from "../assets/images/menPerfume/men7.jpg";
import men8 from "../assets/images/menPerfume/men8.jpg";
import men9 from "../assets/images/menPerfume/men9.jpg";
import men10 from "../assets/images/menPerfume/men10.jpg";
import women1 from "../assets/images/womenPerfume/women1.jpg";
import women2 from "../assets/images/womenPerfume/women2.jpg";
import women3 from "../assets/images/womenPerfume/women3.jpg";
import women4 from "../assets/images/womenPerfume/women4.jpg";
import women5 from "../assets/images/womenPerfume/women5.jpg";
import women6 from "../assets/images/womenPerfume/women6.jpg";
import women7 from "../assets/images/womenPerfume/women7.jpg";
import women8 from "../assets/images/womenPerfume/women8.jpg";
import women9 from "../assets/images/womenPerfume/women9.jpg";
import women10 from "../assets/images/womenPerfume/women10.jpg";
// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1005,
    title: "Categories",
    link: "/categories", 
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  

];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    rating: "4",
    reviewName: 'Stephon',
    review: "Amazing Product",
    des: "Cap for boys: A trendy and versatile accessory that adds a cool and sporty flair to any casual outfit",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    rating: "5",
    reviewName: 'Stephon',
    review: "Amazing Product",
    des:
      "Tea table: A stylish and functional centerpiece, perfect for elevating your tea time or enhancing the aesthetic appeal of your living space.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    rating: "4",
    badge: true,
    reviewName: 'Stephon',
    review: "Amazing Product",
    des: "Headphones: Immersive audio experience and comfort combined in a sleek design, delivering high-quality sound for your listening pleasure.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    rating: "5",
    badge: true,
    reviewName: 'Stephon',
    review: "Amazing Product",
    des: "Sun glasses: Fashionable eye protection that blends style and UV defense for a chic and shielded outdoor experience.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "100001",
    img: men1,
    productName: "212 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    price: "42.30",
    Oz: "Black",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 1.7 EAU DE TOILETTE SPRAY FOR MEN  ",
  },
  {
    _id: "100002",
    img: men2,
    productName: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    price: "250.00",
    Oz: "Black",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN ",
  },
  {
    _id: "100003",
    img: men3,
    productName: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    price: "60.00",
    Oz: "Black",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN   ",
  },
  {
    _id: "100004",
    img: men4,
    productName: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    price: "28.00",
    Oz: "3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL   ",
  },
  {
    _id: "100005",
    img: men5,
    productName: "ACQUA DI GIO 0.5 EAU DE PARFUM SPRAY FOR MEN",
    price: "21.00",
    Oz: "0.6",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ACQUA DI GIO 0.5 EAU DE PARFUM SPRAY FOR MEN   ",
  },
  {
    _id: "100006",
    img: men6,
    productName: "ADIDAS PURE GAME 3.3 EAU DE TOILETTE SPRAY FOR MEN",
    price: "5.10",
    Oz: "3.3",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ADIDAS PURE GAME 3.3 EAU DE TOILETTE SPRAY FOR MEN   ",
  },
  {
    _id: "100007",
    img: men7,
    productName: "AFNAN SUPREMACY NOIR 3.4 EAU DE PARFUM SPRAY FOR MEN",
    price: "22.80",
    Oz: "3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "AFNAN SUPREMACY NOIR 3.4 EAU DE PARFUM SPRAY FOR MEN   ",
  },
  {
    _id: "100008",
    img: men8,
    productName: "AL HARAMAIN L'AVENTURE 3.3 EAU DE PARFUM SPRAY FOR MEN",
    price: "26.40",
    Oz: "3.3",
    badge: true,
    rating: 4.5,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "AL HARAMAIN L'AVENTURE 3.3 EAU DE PARFUM SPRAY FOR MEN   ",
  },
  {
    _id: "100009",
    img: men9,
    productName: "AL HARAMAIN L'AVENTURE KNIGHT 3.4 EAU DE PARFUM SPRAY",
    price: "25.80",
    Oz: "3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "AL HARAMAIN L'AVENTURE KNIGHT 3.4 EAU DE PARFUM SPRAY   ",
  },
  {
    _id: "100010",
    img: men10,
    productName: "ALFRED SUNG HEI 3.4 EDT SP",
    price: "14.26",
    Oz: "3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ALFRED SUNG HEI 3.4 EDT SP   ",
  },
  {
    _id: "100001",
    img: women1,
    productName: "212 2 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY FOR WOMEN + 3.4 BODY LOTION.",
    price: "75.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 2 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY FOR WOMEN + 3.4 BODY LOTION.  ",
  },
  {
    _id: "100002",
    img: women2,
    productName: "212 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
    price: "64.80",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 3.4 EAU DE TOILETTE SPRAY FOR WOMEN  ",
  },
  {
    _id: "100003",
    img: women3,
    productName: "212 VIP ROSE 1.7 EAU DE PARFUM SPRAY FOR WOMEN",
    price: "48.00",
    Oz: "1.7",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 VIP ROSE 1.7 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100004",
    img: women4,
    productName: "212 VIP ROSE ELIXIR 5 ML EAU DE PARFUM ELIXIR MINI FOR WOMEN",
    price: "18.80",
    Oz: "0.17",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 VIP ROSE ELIXIR 5 ML EAU DE PARFUM ELIXIR MINI FOR WOMEN  ",
  },
  {
    _id: "100005",
    img: women5,
    productName: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    price: "25.00",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL  ",
  },
  {
    _id: "100006",
    img: women6,
    productName: "ADDICT DIOR 1.7 EAU DE TOILETTE SPRAY",
    price: "75.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "ADDICT DIOR 1.7 EAU DE TOILETTE SPRAY  ",
  },
  {
    _id: "100007",
    img: women7,
    productName: "ADIDAS MOVES 1 OZ EAU DE TOILETTE SPRAY FOR WOMEN",
    price: "12.90",
    Oz: "1",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "ADIDAS MOVES 1 OZ EAU DE TOILETTE SPRAY FOR WOMEN  ",
  },
  {
    _id: "100008",
    img: women8,
    productName: "AFNAN 9 PM POUR FEMME 3.4 EAU DE PARFUM SPRAY",
    price: "23.40",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AFNAN 9 PM POUR FEMME 3.4 EAU DE PARFUM SPRAY  ",
  },
  {
    _id: "100009",
    img: women9,
    productName: "AFNAN SUPREMACY 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    price: "23.40",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AFNAN SUPREMACY 3.4 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100010",
    img: women10,
    productName: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY",
    price: "30.60",
    Oz: "6.7",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY  ",
  },
];
// =================== PaginationItems End here =================
