import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";
import men1 from "../assets/images/menPerfume/men1.jpg";
import men2 from "../assets/images/menPerfume/men2.jpg";
import men3 from "../assets/images/menPerfume/men3.jpg";
import men4 from "../assets/images/menPerfume/men4.jpg";
import men5 from "../assets/images/menPerfume/men5.jpg";
import men6 from "../assets/images/menPerfume/men6.jpg";
import men7 from "../assets/images/menPerfume/men7.jpg";
import men8 from "../assets/images/menPerfume/men8.jpg";
import men9 from "../assets/images/menPerfume/men9.jpg";
import men10 from "../assets/images/menPerfume/men10.jpg";
import women1 from "../assets/images/womenPerfume/women1.jpg";
import women2 from "../assets/images/womenPerfume/women2.jpg";
import women3 from "../assets/images/womenPerfume/women3.jpg";
import women4 from "../assets/images/womenPerfume/women4.jpg";
import women5 from "../assets/images/womenPerfume/women5.jpg";
import women6 from "../assets/images/womenPerfume/women6.jpg";
import women7 from "../assets/images/womenPerfume/women7.jpg";
import women8 from "../assets/images/womenPerfume/women8.jpg";
import women9 from "../assets/images/womenPerfume/women9.jpg";
import women10 from "../assets/images/womenPerfume/women10.jpg";
import gs1 from "../assets/images/giftsets/gs1.jpg";
import gs2 from "../assets/images/giftsets/gs2.jpg";
import gs3 from "../assets/images/giftsets/gs3.jpg";
import gs4 from "../assets/images/giftsets/gs4.jpg";
import gs5 from "../assets/images/giftsets/gs5.jpg";
import gs6 from "../assets/images/giftsets/gs6.jpg";
import gs7 from "../assets/images/giftsets/gs7.jpg";
import gs8 from "../assets/images/giftsets/gs8.jpg";
import gs9 from "../assets/images/giftsets/gs9.jpg";
import gs10 from "../assets/images/giftsets/gs10.jpg";
import test1 from "../assets/images/tester/test1.jpg";
import test2 from "../assets/images/tester/test2.jpg";
import test3 from "../assets/images/tester/test3.jpg";
import test4 from "../assets/images/tester/test4.jpg";
import test5 from "../assets/images/tester/test5.jpg";
import test6 from "../assets/images/tester/test6.jpg";
import test7 from "../assets/images/tester/test7.jpg";
import test8 from "../assets/images/tester/test8.jpg";
import test9 from "../assets/images/tester/test9.jpg";
import test10 from "../assets/images/tester/test10.jpg";
import ch1 from "../assets/images/children/ch1.jpg";
import ch2 from "../assets/images/children/ch2.jpg";
import ch3 from "../assets/images/children/ch3.jpg";
import ch4 from "../assets/images/children/ch4.jpg";
import ch5 from "../assets/images/children/ch5.jpg";
import ch6 from "../assets/images/children/ch6.jpg";
import ch7 from "../assets/images/children/ch7.jpg";
import ch8 from "../assets/images/children/ch8.jpg";
import ch9 from "../assets/images/children/ch9.jpg";
import ch10 from "../assets/images/children/ch19.jpg";
// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1005,
    title: "Categories",
    link: "/categories", 
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  

];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    rating: "4",
    reviewName: 'Stephon',
    review: "Amazing Product",
    des: "Cap for boys: A trendy and versatile accessory that adds a cool and sporty flair to any casual outfit",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    rating: "5",
    reviewName: 'Stephon',
    review: "Amazing Product",
    des:
      "Tea table: A stylish and functional centerpiece, perfect for elevating your tea time or enhancing the aesthetic appeal of your living space.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    rating: "4",
    badge: true,
    reviewName: 'Stephon',
    review: "Amazing Product",
    des: "Headphones: Immersive audio experience and comfort combined in a sleek design, delivering high-quality sound for your listening pleasure.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    rating: "5",
    badge: true,
    reviewName: 'Stephon',
    review: "Amazing Product",
    des: "Sun glasses: Fashionable eye protection that blends style and UV defense for a chic and shielded outdoor experience.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "100001",
    img: men1,
    productName: "212 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    price: "42.30",
    Oz: "Black",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 1.7 EAU DE TOILETTE SPRAY FOR MEN  ",
  },
  {
    _id: "100002",
    img: men2,
    productName: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    price: "250.00",
    Oz: "Black",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN ",
  },
  {
    _id: "100003",
    img: men3,
    productName: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    price: "60.00",
    Oz: "Black",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN   ",
  },
  {
    _id: "100004",
    img: men4,
    productName: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    price: "28.00",
    Oz: "3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL   ",
  },
  {
    _id: "100005",
    img: men5,
    productName: "ACQUA DI GIO 0.5 EAU DE PARFUM SPRAY FOR MEN",
    price: "21.00",
    Oz: "0.6",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ACQUA DI GIO 0.5 EAU DE PARFUM SPRAY FOR MEN   ",
  },
  {
    _id: "100006",
    img: men6,
    productName: "ADIDAS PURE GAME 3.3 EAU DE TOILETTE SPRAY FOR MEN",
    price: "5.10",
    Oz: "3.3",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ADIDAS PURE GAME 3.3 EAU DE TOILETTE SPRAY FOR MEN   ",
  },
  {
    _id: "100007",
    img: men7,
    productName: "AFNAN SUPREMACY NOIR 3.4 EAU DE PARFUM SPRAY FOR MEN",
    price: "22.80",
    Oz: "3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "AFNAN SUPREMACY NOIR 3.4 EAU DE PARFUM SPRAY FOR MEN   ",
  },
  {
    _id: "100008",
    img: men8,
    productName: "AL HARAMAIN L'AVENTURE 3.3 EAU DE PARFUM SPRAY FOR MEN",
    price: "26.40",
    Oz: "3.3",
    badge: true,
    rating: 4.5,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "AL HARAMAIN L'AVENTURE 3.3 EAU DE PARFUM SPRAY FOR MEN   ",
  },
  {
    _id: "100009",
    img: men9,
    productName: "AL HARAMAIN L'AVENTURE KNIGHT 3.4 EAU DE PARFUM SPRAY",
    price: "25.80",
    Oz: "3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "AL HARAMAIN L'AVENTURE KNIGHT 3.4 EAU DE PARFUM SPRAY   ",
  },
  {
    _id: "100010",
    img: men10,
    productName: "ALFRED SUNG HEI 3.4 EDT SP",
    price: "14.26",
    Oz: "3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ALFRED SUNG HEI 3.4 EDT SP   ",
  },
  {
    _id: "100001",
    img: women1,
    productName: "212 2 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY FOR WOMEN + 3.4 BODY LOTION.",
    price: "75.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 2 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY FOR WOMEN + 3.4 BODY LOTION.  ",
  },
  {
    _id: "100002",
    img: women2,
    productName: "212 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
    price: "64.80",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 3.4 EAU DE TOILETTE SPRAY FOR WOMEN  ",
  },
  {
    _id: "100003",
    img: women3,
    productName: "212 VIP ROSE 1.7 EAU DE PARFUM SPRAY FOR WOMEN",
    price: "48.00",
    Oz: "1.7",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 VIP ROSE 1.7 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100004",
    img: women4,
    productName: "212 VIP ROSE ELIXIR 5 ML EAU DE PARFUM ELIXIR MINI FOR WOMEN",
    price: "18.80",
    Oz: "0.17",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 VIP ROSE ELIXIR 5 ML EAU DE PARFUM ELIXIR MINI FOR WOMEN  ",
  },
  {
    _id: "100005",
    img: women5,
    productName: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    price: "25.00",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL  ",
  },
  {
    _id: "100006",
    img: women6,
    productName: "ADDICT DIOR 1.7 EAU DE TOILETTE SPRAY",
    price: "75.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "ADDICT DIOR 1.7 EAU DE TOILETTE SPRAY  ",
  },
  {
    _id: "100007",
    img: women7,
    productName: "ADIDAS MOVES 1 OZ EAU DE TOILETTE SPRAY FOR WOMEN",
    price: "12.90",
    Oz: "1",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "ADIDAS MOVES 1 OZ EAU DE TOILETTE SPRAY FOR WOMEN  ",
  },
  {
    _id: "100008",
    img: women8,
    productName: "AFNAN 9 PM POUR FEMME 3.4 EAU DE PARFUM SPRAY",
    price: "23.40",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AFNAN 9 PM POUR FEMME 3.4 EAU DE PARFUM SPRAY  ",
  },
  {
    _id: "100009",
    img: women9,
    productName: "AFNAN SUPREMACY 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    price: "23.40",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AFNAN SUPREMACY 3.4 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100010",
    img: women10,
    productName: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY",
    price: "30.60",
    Oz: "6.7",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY  ",
  },
  {
    _id: "100001",
    img: gs1,
    productName: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    price: "25.20",
    Oz: "3.4, 0.25 , 3",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL  ",
  },
  {
    _id: "100002",
    img: gs2,
    productName: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    price: "28.80",
    Oz: "3.4, 0.25 , 3",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL ",
  },
  {
    _id: "100003",
    img: gs3,
    productName: "ACQUA DI PARMA BLU MEDITERRANEO 5 X 0.16 EAU DE TOILETTE MINI SET: ARANCIA DI CAPRI + BERGAMOTTO DI CALABRIA + FICO DI AMALFI + MIRTO DI PANAREA + MANDORLO DI SICILIA",
    price: "33.60",
    Oz: "0.16x5",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ACQUA DI PARMA BLU MEDITERRANEO 5 X 0.16 EAU DE TOILETTE MINI SET: ARANCIA DI CAPRI + BERGAMOTTO DI CALABRIA + FICO DI AMALFI + MIRTO DI PANAREA + MANDORLO DI SICILIA   ",
  },
  {
    _id: "100004",
    img: gs4,
    productName: "ANAIS ANAIS 3 PCS SET: 1 OZ EAU DE PARFUM SPRAY + 2 * 1.7 BODY LOTION",
    price: "16.80",
    Oz: "1, 1.7, 1.7",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ANAIS ANAIS 3 PCS SET: 1 OZ EAU DE PARFUM SPRAY + 2 * 1.7 BODY LOTION   ",
  },
  {
    _id: "100005",
    img: gs5,
    productName: "ANIMALE 3 PCS SET FOR WOMEN: 3.4 EAU DE PARFUM SPRAY + 3.4 SHOWER GEL + 3.4 BODY LOTION",
    price: "30.00",
    Oz: "3.4, 3.4, 3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ANIMALE 3 PCS SET FOR WOMEN: 3.4 EAU DE PARFUM SPRAY + 3.4 SHOWER GEL + 3.4 BODY LOTION   ",
  },
  {
    _id: "100006",
    img: gs6,
    productName: "ANNA SUI 6 PC MINI SET FOR WOMEN: FANTASIA 0.17 EAU DE TOILETTE + FANTASIA MERMAID 0.17 EAU DE TOILETTE + SECRET WISH 0.17 EAU DE TOILETTE + 2 X SKY 0.17 EAU DE TOILETTE + POUCH",
    price: "25.20",
    Oz: "0.17x4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ANNA SUI 6 PC MINI SET FOR WOMEN: FANTASIA 0.17 EAU DE TOILETTE + FANTASIA MERMAID 0.17 EAU DE TOILETTE + SECRET WISH 0.17 EAU DE TOILETTE + 2 X SKY 0.17 EAU DE TOILETTE + POUCH   ",
  },
  {
    _id: "100007",
    img: gs7,
    productName: "ARIANA GRANDE ARI 3 PCS SET: 3.4 EAU DE PARFUM SPRAY + 4 OZ BODY MIST + 3.4 BODY SOUFFLE",
    price: "42.00",
    Oz: "3.4, 4, 3.4",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ARIANA GRANDE ARI 3 PCS SET: 3.4 EAU DE PARFUM SPRAY + 4 OZ BODY MIST + 3.4 BODY SOUFFLE   ",
  },
  {
    _id: "100008",
    img: gs8,
    productName: "ARMANI CODE 2 PCS SET FOR MEN: 4.2 EAU DE TOILETTE SPRAY + 0.5 EAU DE TOILETTE SPRAY",
    price: "84.00",
    Oz: "4.2, 0.5",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "ARMANI CODE 2 PCS SET FOR MEN: 4.2 EAU DE TOILETTE SPRAY + 0.5 EAU DE TOILETTE SPRAY   ",
  },
  {
    _id: "100009",
    img: gs9,
    productName: "AZZARO THE MOST WANTED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY INTENSE + 2 * 0.33 EAU DE TOILETTE SPRAY INTENSE",
    price: "72.00",
    Oz: "3.4, 0.33, 0.33",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "AZZARO THE MOST WANTED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY INTENSE + 2 * 0.33 EAU DE TOILETTE SPRAY INTENSE   ",
  },
  {
    _id: "100010",
    img: gs10,
    productName: "AZZARO WANTED 3 PCS SET FOR MEN: 3.4 EAU DE PARFUM SPRAY + 0.33 EAU DE PARFUM SPRAY + 2.5 HAIR & BODY SHAMPOO ",
    price: "72.00",
    Oz: "3.4, 0.33, 2.5",
    badge: true,
    rating: 4,
    reviewName: "Emily W",
    review: "Powerful Performance",
    des: "AZZARO WANTED 3 PCS SET FOR MEN: 3.4 EAU DE PARFUM SPRAY + 0.33 EAU DE PARFUM SPRAY + 2.5 HAIR & BODY SHAMPOO",
  },
  {
    _id: "100001",
    img: test1,
    productName: "212 HEROES TESTER 2.7 EAU DE PARFUM SPRAY FOR WOMEN",
    price: "54.00",
    Oz: "2.7",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 HEROES TESTER 2.7 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100002",
    img: test2,
    productName: "212 VIP ROSE TESTER 4.2 EAU DE PARFUM SPRAY FOR WOMEN",
    price: "54.80",
    Oz: "4.2",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 VIP ROSE TESTER 4.2 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100003",
    img: test3,
    productName: "ALFRED SUNG HOMME TESTER 3.4 EAU DE TOILETTE SPRAY FOR MEN",
    price: "8.40",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "ALFRED SUNG HOMME TESTER 3.4 EAU DE TOILETTE SPRAY FOR MEN  ",
  },
  {
    _id: "100004",
    img: test4,
    productName: "AMARIGE TESTER 3.4 EDT SP",
    price: "39.30",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AMARIGE TESTER 3.4 EDT SP  ",
  },
  {
    _id: "100005",
    img: test5,
    productName: "AMOR AMOR CACHAREL TESTER 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
    price: "18.00",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AMOR AMOR CACHAREL TESTER 3.4 EAU DE TOILETTE SPRAY FOR WOMEN  ",
  },
  {
    _id: "100006",
    img: test6,
    productName: "ANGEL TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    price: "58.80",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "ANGEL TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100007",
    img: test7,
    productName: "ARIANA GRANDE ARI TESTER 3.4 EAU DE PARFUM SPRAY",
    price: "23.40",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "ARIANA GRANDE ARI TESTER 3.4 EAU DE PARFUM SPRAY  ",
  },
  {
    _id: "100008",
    img: test8,
    productName: "ARIANA GRANDE MOD BLUSH TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    price: "31.20",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "ARIANA GRANDE MOD BLUSH TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100009",
    img: test9,
    productName: "BONBON V&R UNBOXED 0.24 EAU DE PARFUM MINI FOR WOMEN",
    price: "12.40",
    Oz: "0.24",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "BONBON V&R UNBOXED 0.24 EAU DE PARFUM MINI FOR WOMEN  ",
  },
  {
    _id: "100010",
    img: test10,
    productName: "BYZANCE TESTER 3 OZ EAU DE PARFUM SPRAY FOR WOMEN",
    price: "23",
    Oz: "3",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY  ",
  },
  {
    _id: "100001",
    img: ch1,
    productName: "DC COMICS CATWOMAN 3.4 EAU DE TOILETTE SPRAY",
    price: "4.80",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DC COMICS CATWOMAN 3.4 EAU DE TOILETTE SPRAY  ",
  },
  {
    _id: "100002",
    img: ch2,
    productName: "DISNEY DAISY DUCK 3.4 EAU DE TOILETTE SPRAY",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "212 VIP ROSE TESTER 4.2 EAU DE PARFUM SPRAY FOR WOMEN  ",
  },
  {
    _id: "100003",
    img: ch3,
    productName: "DISNEY DONALD DUCK 3.4 EAU DE TOILETTE SPRAY",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DISNEY DONALD DUCK 3.4 EAU DE TOILETTE SPRAY  ",
  },
  {
    _id: "100004",
    img: ch4,
    productName: "DISNEY ENCANTO 3.4 EAU DE TOILETTE SPRAY",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DISNEY ENCANTO 3.4 EAU DE TOILETTE SPRAY  ",
  },
  {
    _id: "100005",
    img: ch5,
    productName: "DISNEY FROZEN 2 3.4 EAU DE TOILETTE SPRAY WITH CHARM",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DISNEY FROZEN 2 3.4 EAU DE TOILETTE SPRAY WITH CHARM  ",
  },
  {
    _id: "100006",
    img: ch6,
    productName: "DISNEY FROZEN ANNA 3.4 EAU DE TOILETTE SPRAY.",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DISNEY FROZEN ANNA 3.4 EAU DE TOILETTE SPRAY.  ",
  },
  {
    _id: "100007",
    img: ch7,
    productName: "DISNEY MICKEY MOUSE 3.4 EDT SP",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DISNEY MICKEY MOUSE 3.4 EDT SP  ",
  },
  {
    _id: "100008",
    img: ch8,
    productName: "DISNEY PRINCESS ARIEL 3.4 EDT SP.",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DISNEY PRINCESS ARIEL 3.4 EDT SP.  ",
  },
  {
    _id: "100009",
    img: ch9,
    productName: "DISNEY PRINCESS MOANA 3.4 EAU DE TOILETTE SPRAY",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DISNEY PRINCESS MOANA 3.4 EAU DE TOILETTE SPRAY  ",
  },
  {
    _id: "100010",
    img: ch10,
    productName: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
    price: "6.60",
    Oz: "3.4",
    badge: true,
    rating: 4.5,
    reviewName: "Alex M",
    review: " Great Fragrance",
    des: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
  },
];
// =================== PaginationItems End here =================
