// src/data/productsData.js

import {
    newArrOne,
    newArrTwo,
    newArrThree,
    newArrFour,
    newArrFive,
  } from "../../assets/images/index";
  
  const productsData = {
    electronics: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    office_shipping: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    plumbing: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    safety_security: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    vehicle_maintenance: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    grounds_outdoor: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    heating_cooling: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    electrical_supplies: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    power_transmission: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    storage_workspace: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    material_handling: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    lighting: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    janitorial_cleaning: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    raw_materials: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    food_service: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    hardware_building: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    furniture_decor: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    adhesives_tapes: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    welding_soldering: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    pumps: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    paint_coatings: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    medical_personal_care: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    test_instruments: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    lab_equipment: [
      {
        _id: "100001",
        img: newArrTwo,
        productName: "Round Table Clockkk",
        price: "44.00",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sleek Design",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "250.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
  };
  
  export default productsData;
  