// src/data/productsData.js

import {
    newArrOne,
    newArrTwo,
    newArrThree,
    newArrFour,
    newArrFive,
    electronicsOne,
  } from "../../assets/images/index";
  import tools1 from "../../assets/images/tools/tools1.jpg"
  import tools2 from "../../assets/images/tools/tools2.jpg"
  import tools3 from "../../assets/images/tools/tools3.jpg"
  import tools4 from "../../assets/images/tools/tools4.jpg"
  import tools5 from "../../assets/images/tools/tools5.jpeg"
  import tools6 from "../../assets/images/tools/tools6.jpg"
  import tools7 from "../../assets/images/tools/tools7.jpg"
  import tools8 from "../../assets/images/tools/tools8.jpg"
  import tools9 from "../../assets/images/tools/tools9.jpg"
  import tools10 from "../../assets/images/tools/tools10.jpg"
  import off1 from "../../assets/images/tools/off1.jpg"
  import off2 from "../../assets/images/tools/off2.jpg"
  import off3 from "../../assets/images/tools/off3.jpg"
  import off4 from "../../assets/images/tools/off4.jpg"
  import off5 from "../../assets/images/tools/off5.jpg"
  import off6 from "../../assets/images/tools/off6.jpg"
  import off7 from "../../assets/images/tools/off7.jpg"
  import off8 from "../../assets/images/tools/off8.jpg"
  import off9 from "../../assets/images/tools/off9.jpg"
  import off10 from "../../assets/images/tools/off10.jpeg"
  import plu1 from "../../assets/images/tools/plu1.jpg"
  import plu2 from "../../assets/images/tools/plu2.jpg"
  import plu3 from "../../assets/images/tools/plu3.jpg"
  import plu4 from "../../assets/images/tools/plu4.jpg"
  import plu5 from "../../assets/images/tools/plu5.jpg"
  import plu6 from "../../assets/images/tools/plu6.jpg"
  import plu7 from "../../assets/images/tools/plu7.jpg"
  import plu8 from "../../assets/images/tools/plu8.jpg"
  import plu9 from "../../assets/images/tools/plu9.jpg"
  import plu10 from "../../assets/images/tools/plu10.jpg"
  import s1 from "../../assets/images/tools/s1.jpg"
  import s2 from "../../assets/images/tools/s2.jpg"
  import s3 from "../../assets/images/tools/s3.jpg"
  import s4 from "../../assets/images/tools/s4.jpg"
  import s5 from "../../assets/images/tools/s5.jpg"
  import s6 from "../../assets/images/tools/s6.jpg"
  import s7 from "../../assets/images/tools/s7.jpg"
  import s8 from "../../assets/images/tools/s8.jpg"
  import s9 from "../../assets/images/tools/s9.jpg"
  import s10 from "../../assets/images/tools/s10.jpg"
  import g1 from "../../assets/images/tools/g1.jpg"
  import g2 from "../../assets/images/tools/g2.jpg"
  import g3 from "../../assets/images/tools/g3.jpg"
  import g4 from "../../assets/images/tools/g4.jpg"
  import g5 from "../../assets/images/tools/g5.jpg"
  import g6 from "../../assets/images/tools/g6.jpg"
  import g7 from "../../assets/images/tools/g7.jpg"
  import g8 from "../../assets/images/tools/g8.jpg"
  import g9 from "../../assets/images/tools/g9.jpg"
  import g10 from "../../assets/images/tools/g10.jpg"
  import men1 from "../../assets/images/menPerfume/men1.jpg";
  import men2 from "../../assets/images/menPerfume/men2.jpg";
  import men3 from "../../assets/images/menPerfume/men3.jpg";
  import men4 from "../../assets/images/menPerfume/men4.jpg";
  import men5 from "../../assets/images/menPerfume/men5.jpg";
  import men6 from "../../assets/images/menPerfume/men6.jpg";
  import men7 from "../../assets/images/menPerfume/men7.jpg";
  import men8 from "../../assets/images/menPerfume/men8.jpg";
  import men9 from "../../assets/images/menPerfume/men9.jpg";
  import men10 from "../../assets/images/menPerfume/men10.jpg";
  import women1 from "../../assets/images/womenPerfume/women1.jpg";
  import women2 from "../../assets/images/womenPerfume/women2.jpg";
  import women3 from "../../assets/images/womenPerfume/women3.jpg";
  import women4 from "../../assets/images/womenPerfume/women4.jpg";
  import women5 from "../../assets/images/womenPerfume/women5.jpg";
  import women6 from "../../assets/images/womenPerfume/women6.jpg";
  import women7 from "../../assets/images/womenPerfume/women7.jpg";
  import women8 from "../../assets/images/womenPerfume/women8.jpg";
  import women9 from "../../assets/images/womenPerfume/women9.jpg";
  import women10 from "../../assets/images/womenPerfume/women10.jpg";
  import gs1 from "../../assets/images/giftsets/gs1.jpg";
  import gs2 from "../../assets/images/giftsets/gs2.jpg";
  import gs3 from "../../assets/images/giftsets/gs3.jpg";
  import gs4 from "../../assets/images/giftsets/gs4.jpg";
  import gs5 from "../../assets/images/giftsets/gs5.jpg";
  import gs6 from "../../assets/images/giftsets/gs6.jpg";
  import gs7 from "../../assets/images/giftsets/gs7.jpg";
  import gs8 from "../../assets/images/giftsets/gs8.jpg";
  import gs9 from "../../assets/images/giftsets/gs9.jpg";
  import gs10 from "../../assets/images/giftsets/gs10.jpg";
import test1 from "../../assets/images/tester/test1.jpg";
import test2 from "../../assets/images/tester/test2.jpg";
import test3 from "../../assets/images/tester/test3.jpg";
import test4 from "../../assets/images/tester/test4.jpg";
import test5 from "../../assets/images/tester/test5.jpg";
import test6 from "../../assets/images/tester/test6.jpg";
import test7 from "../../assets/images/tester/test7.jpg";
import test8 from "../../assets/images/tester/test8.jpg";
import test9 from "../../assets/images/tester/test9.jpg";
import test10 from "../../assets/images/tester/test10.jpg";
import ch1 from "../../assets/images/children/ch1.jpg";
import ch2 from "../../assets/images/children/ch2.jpg";
import ch3 from "../../assets/images/children/ch3.jpg";
import ch4 from "../../assets/images/children/ch4.jpg";
import ch5 from "../../assets/images/children/ch5.jpg";
import ch6 from "../../assets/images/children/ch6.jpg";
import ch7 from "../../assets/images/children/ch7.jpg";
import ch8 from "../../assets/images/children/ch8.jpg";
import ch9 from "../../assets/images/children/ch9.jpg";
import ch10 from "../../assets/images/children/ch19.jpg";
import { Children } from "react";

  const productsData = {
    // electronics: [
    //   {
    //     _id: "100001",
    //     img: newArrFive,
    //     productName: "19PC SHOCKWAVE Impact Duty 1/2 Drive SAE Deep 6 Point Socket Set",
    //     price: "44.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "Product details about the MILWAUKEE TOOL - 49-66-7012 IMPACT SOCKET SET.An impact socket set is a specialized tool kit designed for use with impact wrenches or drivers. These sockets are constructed with durable materials, often featuring a thicker build to withstand the high torque produced by impact tools. The impact socket set is essential for tasks where regular sockets may fail under the force generated by impact wrenches, making it a reliable choice for automotive repairs, construction, and other heavy-duty applications. The set typically includes a variety of socket sizes to accommodate different fastener types.The Milwaukee Tool - 49-66-7012 Impact Socket Set is a comprehensive collection designed to accommodate various bolt clearances ranging from 15/16 in to 1 13/16 in. The set includes deep sockets of sizes between 3/8 in and 1 1/2 in, making it suitable for diverse applications. With a total of nineteen deep sockets included, each socket size is specifically tailored to fit adapters, drivers, ratchets, and wrenches.Crafted from robust steel material with a black phosphate finish, this impact socket set is built for durability and longevity. Each socket features a six-point shape that provides an enhanced grip on fasteners while reducing the risk of rounding them off. The wall thickness varies between 1/8 inch and 3/16 inch which contributes to the strength of these tools. These sockets are not insulated but they are non-sparking and non-magnetic.This impact-rated set comes neatly packed within a plastic case that measures approximately three inches wide by ten inches high by sixteen inches long. This container's compact dimensions make it convenient for storage or transport while its carrying case feature allows easy accessibility during work sessions. Although this kit does not include flex sockets or standard sockets, it offers compatibility with SAE drive types and meets ASME standards.In conclusion, the Milwaukee Tool -49-66-7012 Impact Socket Set is an essential toolset designed for professionals across industries such as electrical services, fabricated metals production, general approach tasks or transportation services who require reliable tools that can withstand heavy-duty use.",
    //   },
    //   {
    //     _id: "100002",
    //     img: newArrTwo,
    //     productName: "Smart Watch",
    //     price: "16.97",
    //     color: "Red",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "25 ft. Compact Tape Measure",
    //   },
    // ],
    // office_shipping: [
    //   {
    //     _id: "100001",
    //     img: off1,
    //     productName: "Tape Dispenser",
    //     price: "44.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "Tape Dispenser, Handheld, For Tape 2 in W, 3 in Core Dia, 11 3/4 in L, Pistol Grip, Blue",
    //   },
    //   {
    //     _id: "100002",
    //     img: off2,
    //     productName: "Packaging Tape",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Packaging Tape, 48mm W, 100m L, 2 mil Thick, Clear, Standard Duty, 6 Pack.",
    //   },
    //   {
    //     _id: "100003",
    //     img: off3,
    //     productName: "Cabinet",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Cabinet, Flat File, 5 Drawer, Black",
    //   },
    //   {
    //     _id: "100004",
    //     img: off4,
    //     productName: "Strapping Seal",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Strapping Seal, 3/4 in W, 1 1/4 in L, Open Seals, Steel, Flat",
    //   },
    //   {
    //     _id: "100005",
    //     img: off5,
    //     productName: "Strapping Seal",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Strapping Seal, 3/4 In., Open, PK250",
    //   },
    //   {
    //     _id: "100006",
    //     img: off6,
    //     productName: "Hand Stretch Wrap",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Hand Stretch Wrap, 18 in W x 1500 ft L, 80 ga, Cast Style, Clear, Standard Duty.",
    //   },
    //   {
    //     _id: "100007",
    //     img: off7,
    //     productName: "Hand Stretch Wrap",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Hand Stretch Wrap 5 x 1000 ft., Cast Style, Clear, 4PK",
    //   },
    //   {
    //     _id: "100008",
    //     img: off8,
    //     productName: " Monthly Desk Pad Calendar",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "EcoLogix Monthly Desk Pad Calendar, 22 x 17, White/Green Sheets, 12-Month (Jan to Dec): 2025",
    //   },
    //   {
    //     _id: "100009",
    //     img: off9,
    //     productName: "Calculator",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Construction Calculator, 6 Lx3 1/4 In W",
    //   },
    //   {
    //     _id: "1000010",
    //     img: off10,
    //     productName: "Dry Erase Board",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Dry Erase Board, Easel Mounted, 34x27",
    //   },
    // ],
    // plumbing: [
    //   {
    //     _id: "100001",
    //     img: plu1,
    //     productName: "Water Spray Nozzle",
    //     price: "44.00",
    //     color: "Orange",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "Pistol Grip Water Spray Nozzle, 3/4 in FGHT, 100 psi, 6.5 gpm, 5 in L, Orange",
    //   },
    //   {
    //     _id: "100002",
    //     img: plu2,
    //     productName: "Lever Handle",
    //     price: "250.00",
    //     color: "Silver",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Lever Handle 8 Mount, Commercial 2 Hole Straight Service Sink Faucet",
    //   },
    //   {
    //     _id: "100003",
    //     img: plu3,
    //     productName: "2 Hole Low Arc Kitchen Faucet",
    //     price: "250.00",
    //     color: "Silver",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Manual, 8 Mount, 2 Hole Low Arc Kitchen Faucet",
    //   },
    //   {
    //     _id: "100004",
    //     img: plu4,
    //     productName: "Ball Valve",
    //     price: "250.00",
    //     color: "Silver",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Ball Valve, 2 in Pipe, Full Port, 600 psi CWP, Lever Handle, FNPT, Chrome Plated Brass",
    //   },
    //   {
    //     _id: "100005",
    //     img: plu5,
    //     productName: "Hose Bibb",
    //     price: "250.00",
    //     color: "Silver",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Hose Bibb, MPT, 3/4 in., T-Handle",
    //   },
    //   {
    //     _id: "100006",
    //     img: plu6,
    //     productName: "Connector",
    //     price: "250.00",
    //     color: "White",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "1-1/2 x 1-1/2 Dia, Valve: ABS; Membrane: Silicone; Cover: Styrofoam; Connector: Rubber, White",
    //   },
    //   {
    //     _id: "100007",
    //     img: plu7,
    //     productName: "Slip Connection",
    //     price: "250.00",
    //     color: "White",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "P-Trap, 1-1/2 in Pipe Size, Slip Connection, 10 in Overall Lg, Plastic, White",
    //   },
    //   {
    //     _id: "100008",
    //     img: plu8,
    //     productName: "Sink",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "17.25 W x 17.25 L x Granite Composite",
    //   },
    //   {
    //     _id: "100009",
    //     img: plu9,
    //     productName: "Toilet Seat",
    //     price: "250.00",
    //     color: "Silver",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Elongated Toilet Seat W/Cover, Closed Front, External Check Hinge, 2in Seat H, 14-1/8in W, Wood, White",
    //   },
    //   {
    //     _id: "1000010",
    //     img: plu10,
    //     productName: "Framed Mirror",
    //     price: "250.00",
    //     color: "Silver",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Framed Mirror, Wall Mount, 36 in H x 18 in W x3/4 in D, Stainless Steel, Bright Annealed Finish",
    //   },
    // ],
    // safety_security: [
    //   {
    //     _id: "100001",
    //     img: s1,
    //     productName: "Premium Nitrile Disposable Gloves",
    //     price: "44.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "Premium Nitrile Disposable Gloves, 6 mil, Powder-Free, Fully Textured, L, 100 PK, Black",
    //   },
    //   {
    //     _id: "100002",
    //     img: s2,
    //     productName: "Disposable Nitrile Gloves",
    //     price: "16.15",
    //     color: "Blue",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "TouchNTuff 92-675, Disposable Nitrile Gloves, Textured Fingertips, 4.3 mil Palm, Powder-Free, S",
    //   },
    //   {
    //     _id: "100003",
    //     img: s3,
    //     productName: "Leather Palm Gloves",
    //     price: "4.25",
    //     color: "White",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Leather Palm Gloves, Cowhide, Gunn Cut, Full Finger, Safety Cuff, Cotton/Poly Liner, Gray, L, 1 PR",
    //   },
    //   {
    //     _id: "100004",
    //     img: s4,
    //     productName: " Anti-Fog/Anti-Scratch",
    //     price: "26.15",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Bionic Shield Assembly with Ratchet Adjustment Suspension, Anti-Fog/Anti-Scratch, Clear Lens",
    //   },
    //   {
    //     _id: "100005",
    //     img: s5,
    //     productName: "Faceshield Visor",
    //     price: "38.19",
    //     color: "white",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Faceshield Visor, Clear 6 1/2 in Height, Universal Adapter Suspension",
    //   },
    //   {
    //     _id: "100006",
    //     img: s6,
    //     productName: "High-Visibility Vest",
    //     price: "19,87",
    //     color: "Yellow",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "High-Visibility Vest, Type R, ANSI Class 2, U-Block, Silver Stripe, Zipper, Mesh Polyester, Lime, XL",
    //   },
    //   {
    //     _id: "100007",
    //     img: s7,
    //     productName: "PVC Work Boots",
    //     price: "18,87",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Chesapeake Plain-Toe PVC Work Boots, Waterproof, Defined Heel, Oil Resistant Sole, Black, Size 10",
    //   },
    //   {
    //     _id: "100008",
    //     img: s8,
    //     productName: "Yellow Wet Floor Sign",
    //     price: "15.78",
    //     color: "Yellow",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Bilingual Yellow Wet Floor Sign, 12.05 x 1.55 x 24.3",
    //   },
    //   {
    //     _id: "100009",
    //     img: s9,
    //     productName: "Exit Sign",
    //     price: "19.99",
    //     color: "White",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Exit Sign, Emergency Battery Backup, 7 1/4 in H x 11 5/8 in W, LED, 1 or 2 Faces, White/Red",
    //   },
    //   {
    //     _id: "1000010",
    //     img: s10,
    //     productName: "Traffic Paddle Sign",
    //     price: "23.99",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Traffic Paddle Sign, 2-Sided Stop/Slow, Non-Reflective, 18 in HxW, 9 in Polygrip Handle",
    //   },
    // ],
    // tools: [
    //   {
    //     _id: "100001",
    //     img: tools1,
    //     productName: " Measure Tape",
    //     price: "22.95",
    //     color: "Yellow",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "25 ft FATMAX Classic Tape Measure, 1-1/4 in Blade, Stud Markings, ABS Plastic Case, Rubber Grip",
    //   },
    //   {
    //     _id: "100002",
    //     img: tools2,
    //     productName: "Measure Tape",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "25 ft. Compact Tape Measure",
    //   },
    //   {
    //     _id: "100003",
    //     img: tools3,
    //     productName: "Point Socket Set",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "19PC SHOCKWAVE Impact Duty 1/2 Drive SAE Deep 6 Point Socket Set",
    //   },
    //   {
    //     _id: "100004",
    //     img: tools4,
    //     productName: "Square Drive Socket Set",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "1/4 Hex, 1/2 Square; 3/8 x 7/16, 1/2 x 9/16, 5/8 x 11/16, 3/4 x 13/16, and 7/8 x 15/16 Drive",
    //   },
    //   {
    //     _id: "100005",
    //     img: tools5,
    //     productName: "Titanium Drill Bit Set",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "SHOCKWAVE Impact Duty RED HELIX Titanium Drill Bit Set, TiN Kit, 23-Piece",
    //   },
    //   {
    //     _id: "100006",
    //     img: tools6,
    //     productName: "Cobalt Jobber Length Drill Bit Set",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "29 Piece Cobalt Jobber Length Drill Bit Set, 1/16 - 1/2, Round Bit Cooler Case, DWDCO Series",
    //   },
    //   {
    //     _id: "100007",
    //     img: tools7,
    //     productName: "Fluted Tapered Knob",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "Fluted Tapered Knob, 1/2-13 Thread Size, 4.95L, Blind Tap, HR Phenolic",
    //   },
    //   {
    //     _id: "100008",
    //     img: tools8,
    //     productName: "Pointed Control Knob",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "Pointed Control Knob, 1/4 Thread Size, 0.57L, GP Phenolic",
    //   },
    //   {
    //     _id: "100009",
    //     img: tools9,
    //     productName: "Tool Box",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "PACKOUT 4-Drawer Tool Box, Polymer, Black/Red, 22 in W x 16-1/2 in D x 14-1/2 in H",
    //   },
    //   {
    //     _id: "100010",
    //     img: tools10,
    //     productName: "PACKOUT Large Tool Box",
    //     price: "19.97",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Excellent Performance",
    //     des: "PACKOUT Large Tool Box, Polymer, Black/Red, 22 in W x 16-1/4 in D x 11 in H",
    //   },
    // ],
    // grounds_outdoor: [
    //   {
    //     _id: "100001",
    //     img: g1,
    //     productName: "Drain Spade Shovel",
    //     price: "22.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "14 ga Drain Spade Shovel, Steel Blade, 46-3/4 in L Yellow Fiberglass Handle",
    //   },
    //   {
    //     _id: "100002",
    //     img: g2,
    //     productName: "Scoop Shovel",
    //     price: "33.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "12 Scoop Shovel, Plastic Blade, 30 in L Black Wood Handle",
    //   },
    //   {
    //     _id: "100003",
    //     img: g3,
    //     productName: "Hygienic Square Point Shovel",
    //     price: "35.00",
    //     color: "Blue",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Hygienic Square Point Shovel, Polypropylene Blade, 28 in L, Blue, Polypropylene Handle",
    //   },
    //   {
    //     _id: "100004",
    //     img: g4,
    //     productName: "Hot Water Hose",
    //     price: "33.20",
    //     color: "Red",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "25 ft L Hot Water Hose, 5/8 in Inside Dia, Red, Rubber",
    //   },
    //   {
    //     _id: "100005",
    //     img: g5,
    //     productName: " Hot Water Nozzle",
    //     price: "22.60",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Gilmour 1 Pattern Solid Stream Zinc Hot Water Nozzle",
    //   },
    //   {
    //     _id: "100006",
    //     img: g6,
    //     productName: "Double Tent",
    //     price: "398.88",
    //     color: "Green",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Double Tent Cot w/Rainfly",
    //   },
    //   {
    //     _id: "100007",
    //     img: g7,
    //     productName: "Fan Trellis",
    //     price: "21.25",
    //     color: "Brown",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "48 BRN WD Fan Trellis",
    //   },
    //   {
    //     _id: "100008",
    //     img: g8,
    //     productName: "Windmill",
    //     price: "109.99",
    //     color: "Green",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Classic 8 Foot Windmill",
    //   },
    //   {
    //     _id: "100009",
    //     img: g9,
    //     productName: "Leaf Rake",
    //     price: "35.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Leaf Rake, Aluminum, 17-1/2 L.",
    //   },
    //   {
    //     _id: "100010",
    //     img: g10,
    //     productName: "Netting",
    //     price: "31.25/ea",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "Poultry Netting, Height 72 In, 50 Ft.",
    //   },
    // ],
   
    // janitorial_cleaning: [
    //   {
    //     _id: "100001",
    //     img: newArrOne,
    //     productName: "Round Table Clock",
    //     price: "44.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "A timeless and decorative timepiece for any tabletop or desk.",
    //   },
    //   {
    //     _id: "100002",
    //     img: newArrTwo,
    //     productName: "Smart Watch",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "A wearable device merging style and technology with fitness tracking.",
    //   },
    // ],
    
    // food_service: [
    //   {
    //     _id: "100001",
    //     img: newArrOne,
    //     productName: "Round Table Clock",
    //     price: "44.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "A timeless and decorative timepiece for any tabletop or desk.",
    //   },
    //   {
    //     _id: "100002",
    //     img: newArrTwo,
    //     productName: "Smart Watch",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "A wearable device merging style and technology with fitness tracking.",
    //   },
    // ],
    // test_instruments: [
    //   {
    //     _id: "100001",
    //     img: newArrOne,
    //     productName: "Round Table Clock",
    //     price: "44.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Sleek Design",
    //     des: "A timeless and decorative timepiece for any tabletop or desk.",
    //   },
    //   {
    //     _id: "100002",
    //     img: newArrTwo,
    //     productName: "Smart Watch",
    //     price: "250.00",
    //     color: "Black",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Powerful Performance",
    //     des: "A wearable device merging style and technology with fitness tracking.",
    //   },
    // ],
   
    perfumes: [
      {
        _id: "100001",
        img: gs1,
        productName: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
        price: "25.20",
        Oz: "3.4, 0.25 , 3",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL  ",
      },
      {
        _id: "100002",
        img: gs2,
        productName: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
        price: "28.80",
        Oz: "3.4, 0.25 , 3",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL ",
      },
      {
        _id: "100003",
        img: gs3,
        productName: "ACQUA DI PARMA BLU MEDITERRANEO 5 X 0.16 EAU DE TOILETTE MINI SET: ARANCIA DI CAPRI + BERGAMOTTO DI CALABRIA + FICO DI AMALFI + MIRTO DI PANAREA + MANDORLO DI SICILIA",
        price: "33.60",
        Oz: "0.16x5",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ACQUA DI PARMA BLU MEDITERRANEO 5 X 0.16 EAU DE TOILETTE MINI SET: ARANCIA DI CAPRI + BERGAMOTTO DI CALABRIA + FICO DI AMALFI + MIRTO DI PANAREA + MANDORLO DI SICILIA   ",
      },
      {
        _id: "100004",
        img: gs4,
        productName: "ANAIS ANAIS 3 PCS SET: 1 OZ EAU DE PARFUM SPRAY + 2 * 1.7 BODY LOTION",
        price: "16.80",
        Oz: "1, 1.7, 1.7",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ANAIS ANAIS 3 PCS SET: 1 OZ EAU DE PARFUM SPRAY + 2 * 1.7 BODY LOTION   ",
      },
      {
        _id: "100005",
        img: gs5,
        productName: "ANIMALE 3 PCS SET FOR WOMEN: 3.4 EAU DE PARFUM SPRAY + 3.4 SHOWER GEL + 3.4 BODY LOTION",
        price: "30.00",
        Oz: "3.4, 3.4, 3.4",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ANIMALE 3 PCS SET FOR WOMEN: 3.4 EAU DE PARFUM SPRAY + 3.4 SHOWER GEL + 3.4 BODY LOTION   ",
      },
      {
        _id: "100006",
        img: gs6,
        productName: "ANNA SUI 6 PC MINI SET FOR WOMEN: FANTASIA 0.17 EAU DE TOILETTE + FANTASIA MERMAID 0.17 EAU DE TOILETTE + SECRET WISH 0.17 EAU DE TOILETTE + 2 X SKY 0.17 EAU DE TOILETTE + POUCH",
        price: "25.20",
        Oz: "0.17x4",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ANNA SUI 6 PC MINI SET FOR WOMEN: FANTASIA 0.17 EAU DE TOILETTE + FANTASIA MERMAID 0.17 EAU DE TOILETTE + SECRET WISH 0.17 EAU DE TOILETTE + 2 X SKY 0.17 EAU DE TOILETTE + POUCH   ",
      },
      {
        _id: "100007",
        img: gs7,
        productName: "ARIANA GRANDE ARI 3 PCS SET: 3.4 EAU DE PARFUM SPRAY + 4 OZ BODY MIST + 3.4 BODY SOUFFLE",
        price: "42.00",
        Oz: "3.4, 4, 3.4",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ARIANA GRANDE ARI 3 PCS SET: 3.4 EAU DE PARFUM SPRAY + 4 OZ BODY MIST + 3.4 BODY SOUFFLE   ",
      },
      {
        _id: "100008",
        img: gs8,
        productName: "ARMANI CODE 2 PCS SET FOR MEN: 4.2 EAU DE TOILETTE SPRAY + 0.5 EAU DE TOILETTE SPRAY",
        price: "84.00",
        Oz: "4.2, 0.5",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ARMANI CODE 2 PCS SET FOR MEN: 4.2 EAU DE TOILETTE SPRAY + 0.5 EAU DE TOILETTE SPRAY   ",
      },
      {
        _id: "100009",
        img: gs9,
        productName: "AZZARO THE MOST WANTED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY INTENSE + 2 * 0.33 EAU DE TOILETTE SPRAY INTENSE",
        price: "72.00",
        Oz: "3.4, 0.33, 0.33",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "AZZARO THE MOST WANTED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY INTENSE + 2 * 0.33 EAU DE TOILETTE SPRAY INTENSE   ",
      },
      {
        _id: "100010",
        img: gs10,
        productName: "AZZARO WANTED 3 PCS SET FOR MEN: 3.4 EAU DE PARFUM SPRAY + 0.33 EAU DE PARFUM SPRAY + 2.5 HAIR & BODY SHAMPOO ",
        price: "72.00",
        Oz: "3.4, 0.33, 2.5",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "AZZARO WANTED 3 PCS SET FOR MEN: 3.4 EAU DE PARFUM SPRAY + 0.33 EAU DE PARFUM SPRAY + 2.5 HAIR & BODY SHAMPOO",
      },
    ],
   male: [
      {
        _id: "100001",
        img: men1,
        productName: "212 1.7 EAU DE TOILETTE SPRAY FOR MEN",
        price: "42.30",
        Oz: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "212 1.7 EAU DE TOILETTE SPRAY FOR MEN  ",
      },
      {
        _id: "100002",
        img: men2,
        productName: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
        price: "250.00",
        Oz: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN ",
      },
      {
        _id: "100003",
        img: men3,
        productName: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
        price: "60.00",
        Oz: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN   ",
      },
      {
        _id: "100004",
        img: men4,
        productName: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
        price: "28.00",
        Oz: "3.4",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL   ",
      },
      {
        _id: "100005",
        img: men5,
        productName: "ACQUA DI GIO 0.5 EAU DE PARFUM SPRAY FOR MEN",
        price: "21.00",
        Oz: "0.6",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ACQUA DI GIO 0.5 EAU DE PARFUM SPRAY FOR MEN   ",
      },
      {
        _id: "100006",
        img: men6,
        productName: "ADIDAS PURE GAME 3.3 EAU DE TOILETTE SPRAY FOR MEN",
        price: "5.10",
        Oz: "3.3",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ADIDAS PURE GAME 3.3 EAU DE TOILETTE SPRAY FOR MEN   ",
      },
      {
        _id: "100007",
        img: men7,
        productName: "AFNAN SUPREMACY NOIR 3.4 EAU DE PARFUM SPRAY FOR MEN",
        price: "22.80",
        Oz: "3.4",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "AFNAN SUPREMACY NOIR 3.4 EAU DE PARFUM SPRAY FOR MEN   ",
      },
      {
        _id: "100008",
        img: men8,
        productName: "AL HARAMAIN L'AVENTURE 3.3 EAU DE PARFUM SPRAY FOR MEN",
        price: "26.40",
        Oz: "3.3",
        badge: true,
        rating: 4.5,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "AL HARAMAIN L'AVENTURE 3.3 EAU DE PARFUM SPRAY FOR MEN   ",
      },
      {
        _id: "100009",
        img: men9,
        productName: "AL HARAMAIN L'AVENTURE KNIGHT 3.4 EAU DE PARFUM SPRAY",
        price: "25.80",
        Oz: "3.4",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "AL HARAMAIN L'AVENTURE KNIGHT 3.4 EAU DE PARFUM SPRAY   ",
      },
      {
        _id: "100010",
        img: men10,
        productName: "ALFRED SUNG HEI 3.4 EDT SP",
        price: "14.26",
        Oz: "3.4",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Powerful Performance",
        des: "ALFRED SUNG HEI 3.4 EDT SP   ",
      },
    ],
    female: [
      {
        _id: "100001",
        img: women1,
        productName: "212 2 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY FOR WOMEN + 3.4 BODY LOTION.",
        price: "75.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "212 2 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY FOR WOMEN + 3.4 BODY LOTION.  ",
      },
      {
        _id: "100002",
        img: women2,
        productName: "212 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
        price: "64.80",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "212 3.4 EAU DE TOILETTE SPRAY FOR WOMEN  ",
      },
      {
        _id: "100003",
        img: women3,
        productName: "212 VIP ROSE 1.7 EAU DE PARFUM SPRAY FOR WOMEN",
        price: "48.00",
        Oz: "1.7",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "212 VIP ROSE 1.7 EAU DE PARFUM SPRAY FOR WOMEN  ",
      },
      {
        _id: "100004",
        img: women4,
        productName: "212 VIP ROSE ELIXIR 5 ML EAU DE PARFUM ELIXIR MINI FOR WOMEN",
        price: "18.80",
        Oz: "0.17",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "212 VIP ROSE ELIXIR 5 ML EAU DE PARFUM ELIXIR MINI FOR WOMEN  ",
      },
      {
        _id: "100005",
        img: women5,
        productName: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
        price: "25.00",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL  ",
      },
      {
        _id: "100006",
        img: women6,
        productName: "ADDICT DIOR 1.7 EAU DE TOILETTE SPRAY",
        price: "75.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "ADDICT DIOR 1.7 EAU DE TOILETTE SPRAY  ",
      },
      {
        _id: "100007",
        img: women7,
        productName: "ADIDAS MOVES 1 OZ EAU DE TOILETTE SPRAY FOR WOMEN",
        price: "12.90",
        Oz: "1",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "ADIDAS MOVES 1 OZ EAU DE TOILETTE SPRAY FOR WOMEN  ",
      },
      {
        _id: "100008",
        img: women8,
        productName: "AFNAN 9 PM POUR FEMME 3.4 EAU DE PARFUM SPRAY",
        price: "23.40",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "AFNAN 9 PM POUR FEMME 3.4 EAU DE PARFUM SPRAY  ",
      },
      {
        _id: "100009",
        img: women9,
        productName: "AFNAN SUPREMACY 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
        price: "23.40",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "AFNAN SUPREMACY 3.4 EAU DE PARFUM SPRAY FOR WOMEN  ",
      },
      {
        _id: "100010",
        img: women10,
        productName: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY",
        price: "30.60",
        Oz: "6.7",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY  ",
      },
     
    ],
    tester: [
      {
        _id: "100001",
        img: test1,
        productName: "212 HEROES TESTER 2.7 EAU DE PARFUM SPRAY FOR WOMEN",
        price: "54.00",
        Oz: "2.7",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "212 HEROES TESTER 2.7 EAU DE PARFUM SPRAY FOR WOMEN  ",
      },
      {
        _id: "100002",
        img: test2,
        productName: "212 VIP ROSE TESTER 4.2 EAU DE PARFUM SPRAY FOR WOMEN",
        price: "54.80",
        Oz: "4.2",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "212 VIP ROSE TESTER 4.2 EAU DE PARFUM SPRAY FOR WOMEN  ",
      },
      {
        _id: "100003",
        img: test3,
        productName: "ALFRED SUNG HOMME TESTER 3.4 EAU DE TOILETTE SPRAY FOR MEN",
        price: "8.40",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "ALFRED SUNG HOMME TESTER 3.4 EAU DE TOILETTE SPRAY FOR MEN  ",
      },
      {
        _id: "100004",
        img: test4,
        productName: "AMARIGE TESTER 3.4 EDT SP",
        price: "39.30",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "AMARIGE TESTER 3.4 EDT SP  ",
      },
      {
        _id: "100005",
        img: test5,
        productName: "AMOR AMOR CACHAREL TESTER 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
        price: "18.00",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "AMOR AMOR CACHAREL TESTER 3.4 EAU DE TOILETTE SPRAY FOR WOMEN  ",
      },
      {
        _id: "100006",
        img: test6,
        productName: "ANGEL TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
        price: "58.80",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "ANGEL TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN  ",
      },
      {
        _id: "100007",
        img: test7,
        productName: "ARIANA GRANDE ARI TESTER 3.4 EAU DE PARFUM SPRAY",
        price: "23.40",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "ARIANA GRANDE ARI TESTER 3.4 EAU DE PARFUM SPRAY  ",
      },
      {
        _id: "100008",
        img: test8,
        productName: "ARIANA GRANDE MOD BLUSH TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
        price: "31.20",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "ARIANA GRANDE MOD BLUSH TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN  ",
      },
      {
        _id: "100009",
        img: test9,
        productName: "BONBON V&R UNBOXED 0.24 EAU DE PARFUM MINI FOR WOMEN",
        price: "12.40",
        Oz: "0.24",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "BONBON V&R UNBOXED 0.24 EAU DE PARFUM MINI FOR WOMEN  ",
      },
      {
        _id: "100010",
        img: test10,
        productName: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
        price: "23",
        Oz: "3",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY  ",
      },
     
    ],
    children: [
      {
        _id: "100001",
        img: ch1,
        productName: "DC COMICS CATWOMAN 3.4 EAU DE TOILETTE SPRAY",
        price: "4.80",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DC COMICS CATWOMAN 3.4 EAU DE TOILETTE SPRAY  ",
      },
      {
        _id: "100002",
        img: ch2,
        productName: "DISNEY DAISY DUCK 3.4 EAU DE TOILETTE SPRAY",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "212 VIP ROSE TESTER 4.2 EAU DE PARFUM SPRAY FOR WOMEN  ",
      },
      {
        _id: "100003",
        img: ch3,
        productName: "DISNEY DONALD DUCK 3.4 EAU DE TOILETTE SPRAY",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DISNEY DONALD DUCK 3.4 EAU DE TOILETTE SPRAY  ",
      },
      {
        _id: "100004",
        img: ch4,
        productName: "DISNEY ENCANTO 3.4 EAU DE TOILETTE SPRAY",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DISNEY ENCANTO 3.4 EAU DE TOILETTE SPRAY  ",
      },
      {
        _id: "100005",
        img: ch5,
        productName: "DISNEY FROZEN 2 3.4 EAU DE TOILETTE SPRAY WITH CHARM",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DISNEY FROZEN 2 3.4 EAU DE TOILETTE SPRAY WITH CHARM  ",
      },
      {
        _id: "100006",
        img: ch6,
        productName: "DISNEY FROZEN ANNA 3.4 EAU DE TOILETTE SPRAY.",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DISNEY FROZEN ANNA 3.4 EAU DE TOILETTE SPRAY.  ",
      },
      {
        _id: "100007",
        img: ch7,
        productName: "DISNEY MICKEY MOUSE 3.4 EDT SP",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DISNEY MICKEY MOUSE 3.4 EDT SP  ",
      },
      {
        _id: "100008",
        img: ch8,
        productName: "DISNEY PRINCESS ARIEL 3.4 EDT SP.",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DISNEY PRINCESS ARIEL 3.4 EDT SP.  ",
      },
      {
        _id: "100009",
        img: ch9,
        productName: "DISNEY PRINCESS MOANA 3.4 EAU DE TOILETTE SPRAY",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DISNEY PRINCESS MOANA 3.4 EAU DE TOILETTE SPRAY  ",
      },
      {
        _id: "100010",
        img: ch10,
        productName: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
        price: "6.60",
        Oz: "3.4",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: " Great Fragrance",
        des: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
      },
     
    ],
  };
  
  export default productsData;
  