// src/data/productsData.js

import {
    newArrOne,
    newArrTwo,
    newArrThree,
    newArrFour,
    newArrFive,
    electronicsOne,
  } from "../../assets/images/index";
  import tools1 from "../../assets/images/tools/tools1.jpg"
  import tools2 from "../../assets/images/tools/tools2.jpg"
  import tools3 from "../../assets/images/tools/tools3.jpg"
  import tools4 from "../../assets/images/tools/tools4.jpg"
  import tools5 from "../../assets/images/tools/tools5.jpeg"
  import tools6 from "../../assets/images/tools/tools6.jpg"
  import tools7 from "../../assets/images/tools/tools7.jpg"
  import tools8 from "../../assets/images/tools/tools8.jpg"
  import tools9 from "../../assets/images/tools/tools9.jpg"
  import tools10 from "../../assets/images/tools/tools10.jpg"
  import off1 from "../../assets/images/tools/off1.jpg"
  import off2 from "../../assets/images/tools/off2.jpg"
  import off3 from "../../assets/images/tools/off3.jpg"
  import off4 from "../../assets/images/tools/off4.jpg"
  import off5 from "../../assets/images/tools/off5.jpg"
  import off6 from "../../assets/images/tools/off6.jpg"
  import off7 from "../../assets/images/tools/off7.jpg"
  import off8 from "../../assets/images/tools/off8.jpg"
  import off9 from "../../assets/images/tools/off9.jpg"
  import off10 from "../../assets/images/tools/off10.jpeg"
  import plu1 from "../../assets/images/tools/plu1.jpg"
  import plu2 from "../../assets/images/tools/plu2.jpg"
  import plu3 from "../../assets/images/tools/plu3.jpg"
  import plu4 from "../../assets/images/tools/plu4.jpg"
  import plu5 from "../../assets/images/tools/plu5.jpg"
  import plu6 from "../../assets/images/tools/plu6.jpg"
  import plu7 from "../../assets/images/tools/plu7.jpg"
  import plu8 from "../../assets/images/tools/plu8.jpg"
  import plu9 from "../../assets/images/tools/plu9.jpg"
  import plu10 from "../../assets/images/tools/plu10.jpg"
  import s1 from "../../assets/images/tools/s1.jpg"
  import s2 from "../../assets/images/tools/s2.jpg"
  import s3 from "../../assets/images/tools/s3.jpg"
  import s4 from "../../assets/images/tools/s4.jpg"
  import s5 from "../../assets/images/tools/s5.jpg"
  import s6 from "../../assets/images/tools/s6.jpg"
  import s7 from "../../assets/images/tools/s7.jpg"
  import s8 from "../../assets/images/tools/s8.jpg"
  import s9 from "../../assets/images/tools/s9.jpg"
  import s10 from "../../assets/images/tools/s10.jpg"
  import g1 from "../../assets/images/tools/g1.jpg"
  import g2 from "../../assets/images/tools/g2.jpg"
  import g3 from "../../assets/images/tools/g3.jpg"
  import g4 from "../../assets/images/tools/g4.jpg"
  import g5 from "../../assets/images/tools/g5.jpg"
  import g6 from "../../assets/images/tools/g6.jpg"
  import g7 from "../../assets/images/tools/g7.jpg"
  import g8 from "../../assets/images/tools/g8.jpg"
  import g9 from "../../assets/images/tools/g9.jpg"
  import g10 from "../../assets/images/tools/g10.jpg"
  import men1 from "../../assets/images/menPerfume/men1.jpg";
  import men2 from "../../assets/images/menPerfume/men2.jpg";
  import men3 from "../../assets/images/menPerfume/men3.jpg";
  import men4 from "../../assets/images/menPerfume/men4.jpg";
  import men5 from "../../assets/images/menPerfume/men5.jpg";
  import men6 from "../../assets/images/menPerfume/men6.jpg";
  import men7 from "../../assets/images/menPerfume/men7.jpg";
  import men8 from "../../assets/images/menPerfume/men8.jpg";
  import men9 from "../../assets/images/menPerfume/men9.jpg";
  import men10 from "../../assets/images/menPerfume/men10.jpg";
  import women1 from "../../assets/images/womenPerfume/women1.jpg";
  import women2 from "../../assets/images/womenPerfume/women2.jpg";
  import women3 from "../../assets/images/womenPerfume/women3.jpg";
  import women4 from "../../assets/images/womenPerfume/women4.jpg";
  import women5 from "../../assets/images/womenPerfume/women5.jpg";
  import women6 from "../../assets/images/womenPerfume/women6.jpg";
  import women7 from "../../assets/images/womenPerfume/women7.jpg";
  import women8 from "../../assets/images/womenPerfume/women8.jpg";
  import women9 from "../../assets/images/womenPerfume/women9.jpg";
  import women10 from "../../assets/images/womenPerfume/women10.jpg";
  import gs1 from "../../assets/images/giftsets/gs1.jpg";
  import gs2 from "../../assets/images/giftsets/gs2.jpg";
  import gs3 from "../../assets/images/giftsets/gs3.jpg";
  import gs4 from "../../assets/images/giftsets/gs4.jpg";
  import gs5 from "../../assets/images/giftsets/gs5.jpg";
  import gs6 from "../../assets/images/giftsets/gs6.jpg";
  import gs7 from "../../assets/images/giftsets/gs7.jpg";
  import gs8 from "../../assets/images/giftsets/gs8.jpg";
  import gs9 from "../../assets/images/giftsets/gs9.jpg";
  import gs10 from "../../assets/images/giftsets/gs10.jpg";
import test1 from "../../assets/images/tester/test1.jpg";
import test2 from "../../assets/images/tester/test2.jpg";
import test3 from "../../assets/images/tester/test3.jpg";
import test4 from "../../assets/images/tester/test4.jpg";
import test5 from "../../assets/images/tester/test5.jpg";
import test6 from "../../assets/images/tester/test6.jpg";
import test7 from "../../assets/images/tester/test7.jpg";
import test8 from "../../assets/images/tester/test8.jpg";
import test9 from "../../assets/images/tester/test9.jpg";
import test10 from "../../assets/images/tester/test10.jpg";
import ch1 from "../../assets/images/children/ch1.jpg";
import ch2 from "../../assets/images/children/ch2.jpg";
import ch3 from "../../assets/images/children/ch3.jpg";
import ch4 from "../../assets/images/children/ch4.jpg";
import ch5 from "../../assets/images/children/ch5.jpg";
import ch6 from "../../assets/images/children/ch6.jpg";
import ch7 from "../../assets/images/children/ch7.jpg";
import ch8 from "../../assets/images/children/ch8.jpg";
import ch9 from "../../assets/images/children/ch9.jpg";
import ch10 from "../../assets/images/children/ch19.jpg";
import f1 from "../../assets/images/food/f1.jpg";
import f2 from "../../assets/images/food/f2.jpg";
import f3 from "../../assets/images/food/f3.jpg";
import f4 from "../../assets/images/food/f4.jpg";
import f5 from "../../assets/images/food/f5.jpg";
import f6 from "../../assets/images/food/f6.jpg";
import f7 from "../../assets/images/food/f7.jpg";
import f8 from "../../assets/images/food/f8.jpg";
import f9 from "../../assets/images/food/f9.jpg";
import f10 from "../../assets/images/food/f20.jpg";
import { Children } from "react";

  const productsData = {
    electronics: [
      {
        _id: "100001",
        img: g2,
        productName: "19PC SHOCKWAVE Impact Duty 1/2 Drive SAE Deep 6 Point Socket Set",
        price: "74.99",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Very solid and professional-grade socket set. The fit is precise, and it holds up well under heavy torque without rounding bolts. Great for workshop use.",
        des: "Product details about the MILWAUKEE TOOL - 49-66-7012 IMPACT SOCKET SET.An impact socket set is a specialized tool kit designed for use with impact wrenches or drivers. These sockets are constructed with durable materials, often featuring a thicker build to withstand the high torque produced by impact tools. The impact socket set is essential for tasks where regular sockets may fail under the force generated by impact wrenches, making it a reliable choice for automotive repairs, construction, and other heavy-duty applications. The set typically includes a variety of socket sizes to accommodate different fastener types.The Milwaukee Tool - 49-66-7012 Impact Socket Set is a comprehensive collection designed to accommodate various bolt clearances ranging from 15/16 in to 1 13/16 in. The set includes deep sockets of sizes between 3/8 in and 1 1/2 in, making it suitable for diverse applications. With a total of nineteen deep sockets included, each socket size is specifically tailored to fit adapters, drivers, ratchets, and wrenches.Crafted from robust steel material with a black phosphate finish, this impact socket set is built for durability and longevity. Each socket features a six-point shape that provides an enhanced grip on fasteners while reducing the risk of rounding them off. The wall thickness varies between 1/8 inch and 3/16 inch which contributes to the strength of these tools. These sockets are not insulated but they are non-sparking and non-magnetic.This impact-rated set comes neatly packed within a plastic case that measures approximately three inches wide by ten inches high by sixteen inches long. This container's compact dimensions make it convenient for storage or transport while its carrying case feature allows easy accessibility during work sessions. Although this kit does not include flex sockets or standard sockets, it offers compatibility with SAE drive types and meets ASME standards.In conclusion, the Milwaukee Tool -49-66-7012 Impact Socket Set is an essential toolset designed for professionals across industries such as electrical services, fabricated metals production, general approach tasks or transportation services who require reliable tools that can withstand heavy-duty use."
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "29.99",
        color: "Red",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Surprisingly good for the price. Tracks steps, heart rate, and notifications accurately. Battery lasts a few days, but the app could be better.",
        des: "25 ft. Compact Tape Measure"
      }
    ],
    office_shipping: [
      {
        _id: "100001",
        img: off1,
        productName: "Tape Dispenser",
        price: "18.99",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Sturdy and smooth to use. The weighted base keeps it steady, and cutting tape is effortless without jamming.",
        des: "Tape Dispenser, Handheld, For Tape 2 in W, 3 in Core Dia, 11 3/4 in L, Pistol Grip, Blue",
      },
      {
        _id: "100002",
        img: off2,
        productName: "Packaging Tape",
        price: "12.49",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Strong adhesive and holds boxes securely. Good value for bulk packing and shipping needs.",
        des: "Packaging Tape, 48mm W, 100m L, 2 mil Thick, Clear, Standard Duty, 6 Pack.",
      },
      {
        _id: "100003",
        img: off3,
        productName: "Cabinet",
        price: "189.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Daniel K",
        review: "Spacious and well-built storage cabinet. Drawers slide smoothly and it feels durable for office filing.",
        des: "Cabinet, Flat File, 5 Drawer, Black",
      },
      {
        _id: "100004",
        img: off4,
        productName: "Strapping Seal",
        price: "9.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Sophie R",
        review: "Reliable seals for securing straps. Strong hold and consistent quality in bulk packaging.",
        des: "Strapping Seal, 3/4 in W, 1 1/4 in L, Open Seals, Steel, Flat",
      },
      {
        _id: "100005",
        img: off5,
        productName: "Strapping Seal",
        price: "11.49",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Michael T",
        review: "Works exactly as expected. Easy to apply and holds tightly during shipping.",
        des: "Strapping Seal, 3/4 In., Open, PK250",
      },
      {
        _id: "100006",
        img: off6,
        productName: "Hand Stretch Wrap",
        price: "34.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Laura P",
        review: "Good stretch and cling. Makes pallet wrapping fast and secure without tearing easily.",
        des: "Hand Stretch Wrap, 18 in W x 1500 ft L, 80 ga, Cast Style, Clear, Standard Duty.",
      },
      {
        _id: "100007",
        img: off7,
        productName: "Hand Stretch Wrap",
        price: "29.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Kevin L",
        review: "Decent quality wrap for light to medium packaging. Easy to handle and doesn’t stick unnecessarily.",
        des: "Hand Stretch Wrap 5 x 1000 ft., Cast Style, Clear, 4PK",
      },
      {
        _id: "100008",
        img: off8,
        productName: "Monthly Desk Pad Calendar",
        price: "14.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emma J",
        review: "Clean layout and plenty of writing space. Helps keep daily planning organized.",
        des: "EcoLogix Monthly Desk Pad Calendar, 22 x 17, White/Green Sheets, 12-Month (Jan to Dec): 2025",
      },
      {
        _id: "100009",
        img: off9,
        productName: "Calculator",
        price: "22.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Brian S",
        review: "Simple but effective construction calculator. Buttons are responsive and display is clear.",
        des: "Construction Calculator, 6 Lx3 1/4 In W",
      },
      {
        _id: "1000010",
        img: off10,
        productName: "Dry Erase Board",
        price: "39.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Olivia H",
        review: "Good size for office use. Easy to wipe clean and sturdy easel stand.",
        des: "Dry Erase Board, Easel Mounted, 34x27",
      },
    ],
    plumbing: [
      {
        _id: "100001",
        img: plu1,
        productName: "Water Spray Nozzle",
        price: "12.99",
        color: "Orange",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Solid grip and adjustable spray settings work really well. Feels durable and doesn’t leak under pressure.",
        des: "Pistol Grip Water Spray Nozzle, 3/4 in FGHT, 100 psi, 6.5 gpm, 5 in L, Orange",
      },
      {
        _id: "100002",
        img: plu2,
        productName: "Lever Handle",
        price: "18.50",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "David K",
        review: "Smooth operation and sturdy build. Fits well and works reliably for commercial sink setups.",
        des: "Lever Handle 8 Mount, Commercial 2 Hole Straight Service Sink Faucet",
      },
      {
        _id: "100003",
        img: plu3,
        productName: "2 Hole Low Arc Kitchen Faucet",
        price: "24.99",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Simple design but works efficiently. Water flow is steady and installation is straightforward.",
        des: "Manual, 8 Mount, 2 Hole Low Arc Kitchen Faucet",
      },
      {
        _id: "100004",
        img: plu4,
        productName: "Ball Valve",
        price: "34.99",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Michael R",
        review: "Very reliable valve with strong shutoff control. Feels heavy-duty and well-machined.",
        des: "Ball Valve, 2 in Pipe, Full Port, 600 psi CWP, Lever Handle, FNPT, Chrome Plated Brass",
      },
      {
        _id: "100005",
        img: plu5,
        productName: "Hose Bibb",
        price: "14.25",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Sarah L",
        review: "Easy to install and works smoothly. Good water control and solid metal build.",
        des: "Hose Bibb, MPT, 3/4 in., T-Handle",
      },
      {
        _id: "100006",
        img: plu6,
        productName: "Connector",
        price: "6.49",
        color: "White",
        badge: true,
        rating: 4,
        reviewName: "John P",
        review: "Basic but effective connector. Fits well and seals properly without leakage issues.",
        des: "1-1/2 x 1-1/2 Dia, Valve: ABS; Membrane: Silicone; Cover: Styrofoam; Connector: Rubber, White",
      },
      {
        _id: "100007",
        img: plu7,
        productName: "Slip Connection P-Trap",
        price: "9.99",
        color: "White",
        badge: true,
        rating: 4,
        reviewName: "Kevin T",
        review: "Good quality plastic P-trap. Easy to install and does the job without any issues.",
        des: "P-Trap, 1-1/2 in Pipe Size, Slip Connection, 10 in Overall Lg, Plastic, White",
      },
      {
        _id: "100008",
        img: plu8,
        productName: "Sink",
        price: "129.00",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emma H",
        review: "Looks premium and feels very solid. Scratch resistant and easy to clean.",
        des: "17.25 W x 17.25 L x Granite Composite",
      },
      {
        _id: "100009",
        img: plu9,
        productName: "Toilet Seat",
        price: "39.99",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Brian S",
        review: "Comfortable and easy to install. Hinges feel sturdy and lid closes smoothly.",
        des: "Elongated Toilet Seat W/Cover, Closed Front, External Check Hinge, 2in Seat H, 14-1/8in W, Wood, White",
      },
      {
        _id: "1000010",
        img: plu10,
        productName: "Framed Mirror",
        price: "79.99",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Olivia M",
        review: "Clean and modern look. Mounting was easy and the finish feels high quality.",
        des: "Framed Mirror, Wall Mount, 36 in H x 18 in W x3/4 in D, Stainless Steel, Bright Annealed Finish",
      },
    ],
    safety_security: [
      {
        _id: "100001",
        img: s1,
        productName: "Premium Nitrile Disposable Gloves",
        price: "12.99",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Excellent grip and durability. Comfortable for long use and doesn’t tear easily even during heavy tasks.",
        des: "Premium Nitrile Disposable Gloves, 6 mil, Powder-Free, Fully Textured, L, 100 PK, Black",
      },
      {
        _id: "100002",
        img: s2,
        productName: "Disposable Nitrile Gloves",
        price: "9.49",
        color: "Blue",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Good fit and decent protection. Lightweight but still strong enough for general use.",
        des: "TouchNTuff 92-675, Disposable Nitrile Gloves, Textured Fingertips, 4.3 mil Palm, Powder-Free, S",
      },
      {
        _id: "100003",
        img: s3,
        productName: "Leather Palm Gloves",
        price: "5.99",
        color: "White",
        badge: true,
        rating: 4,
        reviewName: "John D",
        review: "Strong and reliable gloves for construction work. Leather palm adds good protection and grip.",
        des: "Leather Palm Gloves, Cowhide, Gunn Cut, Full Finger, Safety Cuff, Cotton/Poly Liner, Gray, L, 1 PR",
      },
      {
        _id: "100004",
        img: s4,
        productName: "Anti-Fog Safety Face Shield",
        price: "14.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Sarah K",
        review: "Clear visibility and comfortable fit. Anti-fog feature works well even during long shifts.",
        des: "Bionic Shield Assembly with Ratchet Adjustment Suspension, Anti-Fog/Anti-Scratch, Clear Lens",
      },
      {
        _id: "100005",
        img: s5,
        productName: "Faceshield Visor",
        price: "11.99",
        color: "White",
        badge: true,
        rating: 4,
        reviewName: "Michael R",
        review: "Simple but effective protection. Easy to attach and provides good face coverage.",
        des: "Faceshield Visor, Clear 6 1/2 in Height, Universal Adapter Suspension",
      },
      {
        _id: "100006",
        img: s6,
        productName: "High-Visibility Vest",
        price: "8.99",
        color: "Yellow",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Bright and highly visible. Lightweight material makes it comfortable for long wear.",
        des: "High-Visibility Vest, Type R, ANSI Class 2, U-Block, Silver Stripe, Zipper, Mesh Polyester, Lime, XL",
      },
      {
        _id: "100007",
        img: s7,
        productName: "PVC Work Boots",
        price: "24.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "David P",
        review: "Waterproof and durable. Good grip on slippery surfaces and comfortable for daily use.",
        des: "Chesapeake Plain-Toe PVC Work Boots, Waterproof, Defined Heel, Oil Resistant Sole, Black, Size 10",
      },
      {
        _id: "100008",
        img: s8,
        productName: "Yellow Wet Floor Sign",
        price: "10.99",
        color: "Yellow",
        badge: true,
        rating: 4,
        reviewName: "Laura T",
        review: "Bright and easy to notice. Folds easily and is lightweight for quick placement.",
        des: "Bilingual Yellow Wet Floor Sign, 12.05 x 1.55 x 24.3",
      },
      {
        _id: "100009",
        img: s9,
        productName: "Exit Sign",
        price: "19.99",
        color: "White",
        badge: true,
        rating: 4,
        reviewName: "Brian S",
        review: "Bright LED lighting and reliable backup battery. Perfect for emergency compliance.",
        des: "Exit Sign, Emergency Battery Backup, 7 1/4 in H x 11 5/8 in W, LED, 1 or 2 Faces, White/Red",
      },
      {
        _id: "1000010",
        img: s10,
        productName: "Traffic Paddle Sign",
        price: "13.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Olivia M",
        review: "Lightweight and easy to handle. Clear visibility for directing traffic safely.",
        des: "Traffic Paddle Sign, 2-Sided Stop/Slow, Non-Reflective, 18 in HxW, 9 in Polygrip Handle",
      },
    ],
    tools: [
      {
        _id: "100001",
        img: tools1,
        productName: "Measure Tape",
        price: "18.99",
        color: "Yellow",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Very solid tape measure with smooth retraction and strong locking system. Easy to read markings and durable case.",
        des: "25 ft FATMAX Classic Tape Measure, 1-1/4 in Blade, Stud Markings, ABS Plastic Case, Rubber Grip",
      },
      {
        _id: "100002",
        img: tools2,
        productName: "Measure Tape",
        price: "14.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Compact and lightweight. Good for everyday use, but still feels reliable and accurate.",
        des: "25 ft. Compact Tape Measure",
      },
      {
        _id: "100003",
        img: tools3,
        productName: "Point Socket Set",
        price: "39.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "David K",
        review: "Strong and durable socket set. Handles high torque well without slipping or rounding bolts.",
        des: "19PC SHOCKWAVE Impact Duty 1/2 Drive SAE Deep 6 Point Socket Set",
      },
      {
        _id: "100004",
        img: tools4,
        productName: "Square Drive Socket Set",
        price: "24.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Sarah L",
        review: "Good variety of sizes and solid build quality. Works well for both home and workshop use.",
        des: "1/4 Hex, 1/2 Square; 3/8 x 7/16, 1/2 x 9/16, 5/8 x 11/16, 3/4 x 13/16, and 7/8 x 15/16 Drive",
      },
      {
        _id: "100005",
        img: tools5,
        productName: "Titanium Drill Bit Set",
        price: "29.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Michael R",
        review: "Drills smoothly and stays sharp for a long time. Great for metal and wood projects.",
        des: "SHOCKWAVE Impact Duty RED HELIX Titanium Drill Bit Set, TiN Kit, 23-Piece",
      },
      {
        _id: "100006",
        img: tools6,
        productName: "Cobalt Jobber Length Drill Bit Set",
        price: "34.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Kevin T",
        review: "Very strong drill bits, especially good for hard metals. Comes in a well-organized case.",
        des: "29 Piece Cobalt Jobber Length Drill Bit Set, 1/16 - 1/2, Round Bit Cooler Case, DWDCO Series",
      },
      {
        _id: "100007",
        img: tools7,
        productName: "Fluted Tapered Knob",
        price: "9.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emma H",
        review: "Simple but well-made knob. Feels strong and threads fit securely without issues.",
        des: "Fluted Tapered Knob, 1/2-13 Thread Size, 4.95L, Blind Tap, HR Phenolic",
      },
      {
        _id: "100008",
        img: tools8,
        productName: "Pointed Control Knob",
        price: "7.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Brian S",
        review: "Basic control knob but does the job well. Good grip and smooth adjustment.",
        des: "Pointed Control Knob, 1/4 Thread Size, 0.57L, GP Phenolic",
      },
      {
        _id: "100009",
        img: tools9,
        productName: "Tool Box",
        price: "79.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Olivia M",
        review: "Very sturdy and spacious toolbox. Drawers slide smoothly and the modular system is convenient.",
        des: "PACKOUT 4-Drawer Tool Box, Polymer, Black/Red, 22 in W x 16-1/2 in D x 14-1/2 in H",
      },
      {
        _id: "100010",
        img: tools10,
        productName: "PACKOUT Large Tool Box",
        price: "69.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Daniel P",
        review: "Strong and durable storage box. Great for transporting tools safely with good internal space.",
        des: "PACKOUT Large Tool Box, Polymer, Black/Red, 22 in W x 16-1/4 in D x 11 in H",
      },
    ],
    grounds_outdoor: [
      {
        _id: "100001",
        img: g1,
        productName: "Drain Spade Shovel",
        price: "24.99",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Very sturdy shovel with a sharp blade that cuts through soil easily. Comfortable handle grip for long digging jobs.",
        des: "14 ga Drain Spade Shovel, Steel Blade, 46-3/4 in L Yellow Fiberglass Handle",
      },
      {
        _id: "100002",
        img: g2,
        productName: "Scoop Shovel",
        price: "18.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Lightweight and easy to use for moving soil, gravel, or mulch. Handle feels solid and durable.",
        des: "12 Scoop Shovel, Plastic Blade, 30 in L Black Wood Handle",
      },
      {
        _id: "100003",
        img: g3,
        productName: "Hygienic Square Point Shovel",
        price: "21.99",
        color: "Blue",
        badge: true,
        rating: 4,
        reviewName: "David K",
        review: "Good balance and strong build. Easy to clean and works well for landscaping tasks.",
        des: "Hygienic Square Point Shovel, Polypropylene Blade, 28 in L, Blue, Polypropylene Handle",
      },
      {
        _id: "100004",
        img: g4,
        productName: "Hot Water Hose",
        price: "29.99",
        color: "Red",
        badge: true,
        rating: 4,
        reviewName: "Sarah L",
        review: "Flexible and durable hose. Handles hot water without kinking or leaking.",
        des: "25 ft L Hot Water Hose, 5/8 in Inside Dia, Red, Rubber",
      },
      {
        _id: "100005",
        img: g5,
        productName: "Hot Water Nozzle",
        price: "14.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Michael R",
        review: "Simple but effective nozzle. Strong stream and comfortable grip even with hot water use.",
        des: "Gilmour 1 Pattern Solid Stream Zinc Hot Water Nozzle",
      },
      {
        _id: "100006",
        img: g6,
        productName: "Double Tent",
        price: "249.99",
        color: "Green",
        badge: true,
        rating: 4,
        reviewName: "Emma H",
        review: "Spacious and well-designed tent cot. Rainfly works well and setup is fairly easy.",
        des: "Double Tent Cot w/Rainfly",
      },
      {
        _id: "100007",
        img: g7,
        productName: "Fan Trellis",
        price: "19.99",
        color: "Brown",
        badge: true,
        rating: 4,
        reviewName: "Brian S",
        review: "Nice decorative trellis for garden use. Lightweight but stable enough for climbing plants.",
        des: "48 BRN WD Fan Trellis",
      },
      {
        _id: "100008",
        img: g8,
        productName: "Windmill",
        price: "89.99",
        color: "Green",
        badge: true,
        rating: 4,
        reviewName: "Olivia M",
        review: "Beautiful garden feature. Spins smoothly with wind and adds nice outdoor aesthetic.",
        des: "Classic 8 Foot Windmill",
      },
      {
        _id: "100009",
        img: g9,
        productName: "Leaf Rake",
        price: "16.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Daniel P",
        review: "Lightweight and easy to handle. Works well for gathering leaves without damaging grass.",
        des: "Leaf Rake, Aluminum, 17-1/2 L.",
      },
      {
        _id: "100010",
        img: g10,
        productName: "Netting",
        price: "22.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Laura T",
        review: "Strong and flexible netting. Easy to install for poultry or garden protection.",
        des: "Poultry Netting, Height 72 In, 50 Ft.",
      },
    ],
   
    janitorial_cleaning: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "14.99",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Clean and modern design. Keeps accurate time and looks great on office desks or reception areas.",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "79.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Good basic smartwatch for daily use. Tracks fitness well and notifications are reliable, though app could be improved.",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
    
    food_service: [
      {
        _id: "100001",
        img: f1,
        productName: "Cambro CamSquares® Classic 22 Qt. Clear Square Polycarbonate Food Storage Container 22SFSCW135",
        price: "28.99",
        color: "Transparent",
        badge: true,
        rating: 4.5,
        reviewName: "Daniel K",
        review:"Excellent storage container for bulk prep. Very clear material makes it easy to identify contents.",
        des: "A crystal-clear square food storage container ideal for professional kitchen organization and bulk storage.",
      },
    
      {
        _id: "100002",
        img: f2,
        productName: "Baker's Mark 32 Gallon / 510 Cup White Flat Top Ingredient Storage Bin with Lid",
        price: "59.99",
        color: "White",
        badge: true,
        rating: 4,
        reviewName: "Sophie R",
        review: "Huge storage capacity, perfect for flour, rice, and dry ingredients in bulk kitchens.",
       
        des: "Large-capacity ingredient storage bin designed for commercial kitchens and bulk food handling.",
      },
    
      {
        _id: "100003",
        img: f3,
        productName: "Choice 1/6 Size 6 Deep 24 Gauge Anti-Jam Stainless Steel Steam Table / Hotel Pan",
        price: "7.99",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Michael T",
        review:"Solid stainless steel pan, handles high heat very well without warping.",
        des: "Commercial-grade stainless steel steam table pan for hot food holding and serving.",
      },
    
      {
        _id: "100004",
        img: f4,
        productName: "Choice 1/9 Size 6 Deep Anti-Jam Stainless Steel Steam Table / Hotel Pan - 24 Gauge",
        price: "9.99",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Great small-size pan for portioned food service and prep stations.",
          
        des: "Compact stainless steel hotel pan designed for professional food service use.",
      },
    
      {
        _id: "100005",
        img: f5,
        productName: "Choice 6 Hole Steam Table Adapter Plate with 4 3/4 Holes",
        price: "29.99",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Brian H",
        review: "Very useful for customizing steam table layouts for different menu items.",
         
        des: "Adapter plate designed to customize steam table configurations with multiple inset options.",
      },
    
      {
        _id: "100006",
        img: f6,
        productName: "Carlisle CM104902 Coldmaster Full Size White Cold Food Pan Holder with Organizer",
        price: "319.99",
        color: "White",
        badge: true,
        rating: 4,
        reviewName: "Olivia M",
        review:"Excellent for keeping cold food at safe temperature without ice.",
          
        des: "Cold food pan holder designed to maintain safe temperatures without electricity or ice.",
      },
    
      {
        _id: "100007",
        img: f7,
        productName: "1 Gallon Clear Round PET Plastic Jar - 22/Case",
        price: "29.99",
        color: "Clear",
        badge: true,
        rating: 4,
        reviewName: "Jason P",
        review: "Perfect for bulk storage of dry ingredients like spices and grains.",
          
        des: "Clear PET plastic jar designed for bulk storage and ingredient organization.",
      },
    
      {
        _id: "100008",
        img: f8,
        productName: "Choice 1/3 Size 6 Deep 24 Gauge Anti-Jam Stainless Steel Steam Table / Hotel Pan - 12/Set",
        price: "119.99",
        color: "Silver",
        badge: true,
        rating: 4,
        reviewName: "Noah L",
        review: "Reliable hotel pan set for high-volume food service.",
          
        des: "Set of stainless steel hotel pans designed for heavy-duty commercial food service.",
      },
    
      {
        _id: "100009",
        img: f9,
        productName: "Carlisle 3068703 StorPlus 1/9 Size Black Polycarbonate Food Pan - 4 Deep",
        price: "4.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emma J",
        review: "Very affordable and durable food pan for prep stations.",
        
        des: "Durable polycarbonate food pan designed for professional kitchen organization.",
      },
    
      {
        _id: "1000010",
        img: f10,
        productName: "Choice 1/2 Size 6 Deep Clear Polycarbonate Food Pan with Drain Tray and Lid",
        price: "13.99",
        color: "Transparent",
        badge: true,
        rating: 4,
        reviewName: "Liam S",
        review: "Drain tray works perfectly for keeping food fresh and not soggy.",
        
        des: "Clear polycarbonate food pan with drain tray and lid for professional food service.",
      },
    ],
    test_instruments: [
      {
        _id: "100001",
        img: newArrOne,
        productName: "Round Table Clock",
        price: "12.99",
        color: "Black",
        badge: true,
        rating: 4.5,
        reviewName: "Alex M",
        review: "Clean and minimal design. Works reliably and fits well in lab or office environments where simple timing is needed.",
        des: "A timeless and decorative timepiece for any tabletop or desk.",
      },
      {
        _id: "100002",
        img: newArrTwo,
        productName: "Smart Watch",
        price: "59.99",
        color: "Black",
        badge: true,
        rating: 4,
        reviewName: "Emily W",
        review: "Useful for basic monitoring and tracking. Lightweight and easy to use, though not a professional-grade instrument.",
        des: "A wearable device merging style and technology with fitness tracking.",
      },
    ],
   
    // perfumes: [
    //   {
    //     _id: "100001",
    //     img: gs1,
    //     productName: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    //     price: "18.99",
    //     Oz: "3.4, 0.25 , 3",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Fresh and clean fragrance with a light floral touch. Good everyday scent and the set is great value for money.",
    //     des: "360 3 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    //   },
    //   {
    //     _id: "100002",
    //     img: gs2,
    //     productName: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    //     price: "21.99",
    //     Oz: "3.4, 0.25 , 3",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Bold masculine scent with a slightly spicy tone. Long-lasting enough for daily use and gym wear.",
    //     des: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    //   },
    //   {
    //     _id: "100003",
    //     img: gs3,
    //     productName: "ACQUA DI PARMA BLU MEDITERRANEO MINI SET (5 X 0.16 EAU DE TOILETTE)",
    //     price: "59.99",
    //     Oz: "0.16x5",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Daniel K",
    //     review: "Premium luxury scent collection with fresh citrus and aquatic notes. Very refined and elegant fragrances.",
    //     des: "ARANCIA DI CAPRI + BERGAMOTTO DI CALABRIA + FICO DI AMALFI + MIRTO DI PANAREA + MANDORLO DI SICILIA",
    //   },
    //   {
    //     _id: "100004",
    //     img: gs4,
    //     productName: "ANAIS ANAIS 3 PCS SET: 1 OZ EAU DE PARFUM + 2 BODY LOTION",
    //     price: "14.99",
    //     Oz: "1, 1.7, 1.7",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Soft floral fragrance with a classic feminine feel. Lotion adds a nice layering effect for longer wear.",
    //     des: "ANAIS ANAIS 3 PCS SET: 1 OZ EAU DE PARFUM SPRAY + 2 * 1.7 BODY LOTION",
    //   },
    //   {
    //     _id: "100005",
    //     img: gs5,
    //     productName: "ANIMALE 3 PCS SET FOR WOMEN",
    //     price: "24.99",
    //     Oz: "3.4, 3.4, 3.4",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Strong and noticeable fragrance with sweet and warm notes. Good for evening wear.",
    //     des: "ANIMALE 3 PCS SET FOR WOMEN: EAU DE PARFUM + SHOWER GEL + BODY LOTION",
    //   },
    //   {
    //     _id: "100006",
    //     img: gs6,
    //     productName: "ANNA SUI 6 PC MINI SET FOR WOMEN",
    //     price: "29.99",
    //     Oz: "0.17x4",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Fun variety of sweet and playful fragrances. Great for trying different scents before buying full size.",
    //     des: "FANTASIA + MERMAID + SECRET WISH + SKY MINI SET + POUCH",
    //   },
    //   {
    //     _id: "100007",
    //     img: gs7,
    //     productName: "ARIANA GRANDE ARI 3 PCS SET",
    //     price: "34.99",
    //     Oz: "3.4, 4, 3.4",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Sweet and youthful fragrance with a soft vanilla base. Body mist makes it easy to layer scent.",
    //     des: "EAU DE PARFUM + BODY MIST + BODY SOUFFLE",
    //   },
    //   {
    //     _id: "100008",
    //     img: gs8,
    //     productName: "ARMANI CODE 2 PCS SET FOR MEN",
    //     price: "79.99",
    //     Oz: "4.2, 0.5",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Sophisticated and masculine scent. Long-lasting with a strong presence, great for formal occasions.",
    //     des: "ARMANI CODE EAU DE TOILETTE SET",
    //   },
    //   {
    //     _id: "100009",
    //     img: gs9,
    //     productName: "AZZARO THE MOST WANTED 3 PCS SET FOR MEN",
    //     price: "64.99",
    //     Oz: "3.4, 0.33, 0.33",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Warm and spicy fragrance with strong projection. Ideal for night outings and special events.",
    //     des: "EAU DE TOILETTE INTENSE SET",
    //   },
    //   {
    //     _id: "100010",
    //     img: gs10,
    //     productName: "AZZARO WANTED 3 PCS SET FOR MEN",
    //     price: "59.99",
    //     Oz: "3.4, 0.33, 2.5",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Emily W",
    //     review: "Energetic and bold fragrance with a fresh spicy mix. Good balance between casual and formal use.",
    //     des: "EAU DE PARFUM + SPRAY + SHAMPOO SET",
    //   },
    // ],
    // male: [
    //   {
    //     _id: "100001",
    //     img: men1,
    //     productName: "212 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    //     price: "49.99",
    //     Oz: "1.7",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Alex M",
    //     review: "Clean and modern scent. Fresh opening with a slightly woody base that lasts well through the day.",
    //     des: "212 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    //   },
    //   {
    //     _id: "100002",
    //     img: men2,
    //     productName: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    //     price: "54.99",
    //     Oz: "1.7",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "James R",
    //     review: "Bold and slightly sweet fragrance. Great for nights out, strong projection and noticeable presence.",
    //     des: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    //   },
    //   {
    //     _id: "100003",
    //     img: men3,
    //     productName: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    //     price: "59.99",
    //     Oz: "1.7",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Daniel K",
    //     review: "Energetic and youthful scent. Has a party vibe and works well for evening wear.",
    //     des: "212 VIP 1.7 EAU DE TOILETTE SPRAY FOR MEN",
    //   },
    //   {
    //     _id: "100004",
    //     img: men4,
    //     productName: "360 RED 3 PCS SET FOR MEN",
    //     price: "24.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Michael T",
    //     review: "Affordable set with a fresh masculine scent. Shower gel and spray combo makes it good value.",
    //     des: "360 RED 3 PCS SET FOR MEN: 3.4 EAU DE TOILETTE SPRAY + 0.25 EAU DE TOILETTE SPRAY + 3 OZ SHOWER GEL",
    //   },
    //   {
    //     _id: "100005",
    //     img: men5,
    //     productName: "ACQUA DI GIO 0.5 EAU DE PARFUM SPRAY FOR MEN",
    //     price: "34.99",
    //     Oz: "0.5",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "David P",
    //     review: "Fresh aquatic scent with a refined masculine tone. Classic and very versatile for daily wear.",
    //     des: "ACQUA DI GIO 0.5 EAU DE PARFUM SPRAY FOR MEN",
    //   },
    //   {
    //     _id: "100006",
    //     img: men6,
    //     productName: "ADIDAS PURE GAME 3.3 EAU DE TOILETTE SPRAY FOR MEN",
    //     price: "9.99",
    //     Oz: "3.3",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Brian S",
    //     review: "Light sporty fragrance. Very affordable and good for gym or casual daily use.",
    //     des: "ADIDAS PURE GAME 3.3 EAU DE TOILETTE SPRAY FOR MEN",
    //   },
    //   {
    //     _id: "100007",
    //     img: men7,
    //     productName: "AFNAN SUPREMACY NOIR 3.4 EAU DE PARFUM SPRAY FOR MEN",
    //     price: "29.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Omar H",
    //     review: "Strong and elegant scent with dark woody notes. Long-lasting and great for evening wear.",
    //     des: "AFNAN SUPREMACY NOIR 3.4 EAU DE PARFUM SPRAY FOR MEN",
    //   },
    //   {
    //     _id: "100008",
    //     img: men8,
    //     productName: "AL HARAMAIN L'AVENTURE 3.3 EAU DE PARFUM SPRAY FOR MEN",
    //     price: "32.99",
    //     Oz: "3.3",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Kevin L",
    //     review: "Fresh citrus opening with a strong woody base. Very long-lasting and good quality for the price.",
    //     des: "AL HARAMAIN L'AVENTURE 3.3 EAU DE PARFUM SPRAY FOR MEN",
    //   },
    //   {
    //     _id: "100009",
    //     img: men9,
    //     productName: "AL HARAMAIN L'AVENTURE KNIGHT 3.4 EAU DE PARFUM SPRAY",
    //     price: "31.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Ahmed Z",
    //     review: "Rich masculine scent with a smooth blend of fresh and woody notes. Strong performance overall.",
    //     des: "AL HARAMAIN L'AVENTURE KNIGHT 3.4 EAU DE PARFUM SPRAY",
    //   },
    //   {
    //     _id: "100010",
    //     img: men10,
    //     productName: "ALFRED SUNG HEI 3.4 EDT SP",
    //     price: "19.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4,
    //     reviewName: "Eric W",
    //     review: "Classic fresh masculine fragrance. Simple but clean and pleasant for everyday use.",
    //     des: "ALFRED SUNG HEI 3.4 EDT SP",
    //   },
    // ],
    // female: [
    //   {
    //     _id: "100001",
    //     img: women1,
    //     productName: "212 2 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE + BODY LOTION",
    //     price: "59.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Sophie R",
    //     review: "Elegant and clean floral scent. The lotion helps the fragrance last longer and feels soft on the skin.",
    //     des: "212 2 PCS SET FOR WOMEN: 3.4 EAU DE TOILETTE SPRAY FOR WOMEN + 3.4 BODY LOTION.",
    //   },
    //   {
    //     _id: "100002",
    //     img: women2,
    //     productName: "212 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
    //     price: "49.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Emily W",
    //     review: "Fresh and modern feminine scent. Very wearable for daily use and not overpowering.",
    //     des: "212 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100003",
    //     img: women3,
    //     productName: "212 VIP ROSE 1.7 EAU DE PARFUM SPRAY FOR WOMEN",
    //     price: "44.99",
    //     Oz: "1.7",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Isabella K",
    //     review: "Sweet and sparkling fragrance with a party vibe. Perfect for evenings and special occasions.",
    //     des: "212 VIP ROSE 1.7 EAU DE PARFUM SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100004",
    //     img: women4,
    //     productName: "212 VIP ROSE ELIXIR MINI EAU DE PARFUM",
    //     price: "19.99",
    //     Oz: "0.17",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Olivia M",
    //     review: "Small but powerful scent. Sweet and intense, great for carrying in a purse for touch-ups.",
    //     des: "212 VIP ROSE ELIXIR 5 ML EAU DE PARFUM ELIXIR MINI FOR WOMEN",
    //   },
    //   {
    //     _id: "100005",
    //     img: women5,
    //     productName: "360 3 PCS SET FOR WOMEN",
    //     price: "24.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Ava L",
    //     review: "Light and fresh fragrance set. Good everyday scent and nice value with body wash included.",
    //     des: "360 3 PCS SET FOR WOMEN: EAU DE TOILETTE + BODY LOTION + SHOWER GEL",
    //   },
    //   {
    //     _id: "100006",
    //     img: women6,
    //     productName: "DIOR ADDICT 1.7 EAU DE TOILETTE SPRAY",
    //     price: "79.99",
    //     Oz: "1.7",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Charlotte D",
    //     review: "Rich and sophisticated fragrance. Strong presence with a warm, addictive floral scent profile.",
    //     des: "ADDICT DIOR 1.7 EAU DE TOILETTE SPRAY",
    //   },
    //   {
    //     _id: "100007",
    //     img: women7,
    //     productName: "ADIDAS MOVES 1 OZ EAU DE TOILETTE SPRAY FOR WOMEN",
    //     price: "11.99",
    //     Oz: "1",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Mia S",
    //     review: "Light sporty fragrance. Simple and refreshing, good for casual daily wear.",
    //     des: "ADIDAS MOVES 1 OZ EAU DE TOILETTE SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100008",
    //     img: women8,
    //     productName: "AFNAN 9 PM POUR FEMME 3.4 EAU DE PARFUM SPRAY",
    //     price: "29.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Lily H",
    //     review: "Sweet and slightly spicy feminine scent. Long-lasting and very noticeable in a good way.",
    //     des: "AFNAN 9 PM POUR FEMME 3.4 EAU DE PARFUM SPRAY",
    //   },
    //   {
    //     _id: "100009",
    //     img: women9,
    //     productName: "AFNAN SUPREMACY 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    //     price: "27.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Emma J",
    //     review: "Luxurious and warm floral fragrance. Strong projection and good staying power throughout the day.",
    //     des: "AFNAN SUPREMACY 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100010",
    //     img: women10,
    //     productName: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY",
    //     price: "34.99",
    //     Oz: "6.7",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Grace P",
    //     review: "Bold and sensual fragrance with a rich character. Best suited for evening or special occasions.",
    //     des: "AGENT PROVOCATEUR 6.7 EAU DE PARFUM SPRAY",
    //   },
    // ],
    // tester: [
    //   {
    //     _id: "100001",
    //     img: test1,
    //     productName: "212 HEROES TESTER 2.7 EAU DE PARFUM SPRAY FOR WOMEN",
    //     price: "29.99",
    //     Oz: "2.7",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Sophie R",
    //     review: "Fresh and youthful fragrance with a soft sweet touch. Tester version is great value for trying before full purchase.",
    //     des: "212 HEROES TESTER 2.7 EAU DE PARFUM SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100002",
    //     img: test2,
    //     productName: "212 VIP ROSE TESTER 4.2 EAU DE PARFUM SPRAY FOR WOMEN",
    //     price: "34.99",
    //     Oz: "4.2",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Emily W",
    //     review: "Sweet and elegant rose fragrance with a party vibe. Long-lasting and noticeable without being overpowering.",
    //     des: "212 VIP ROSE TESTER 4.2 EAU DE PARFUM SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100003",
    //     img: test3,
    //     productName: "ALFRED SUNG HOMME TESTER 3.4 EAU DE TOILETTE SPRAY FOR MEN",
    //     price: "12.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Daniel K",
    //     review: "Clean classic masculine scent. Simple but very wearable for everyday use.",
    //     des: "ALFRED SUNG HOMME TESTER 3.4 EAU DE TOILETTE SPRAY FOR MEN",
    //   },
    //   {
    //     _id: "100004",
    //     img: test4,
    //     productName: "AMARIGE TESTER 3.4 EDT SP",
    //     price: "24.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Olivia M",
    //     review: "Rich floral fragrance with a vintage feel. Strong and elegant, ideal for special occasions.",
    //     des: "AMARIGE TESTER 3.4 EDT SP",
    //   },
    //   {
    //     _id: "100005",
    //     img: test5,
    //     productName: "AMOR AMOR CACHAREL TESTER 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
    //     price: "19.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Ava L",
    //     review: "Sweet fruity floral scent. Very romantic and perfect for daily wear or date nights.",
    //     des: "AMOR AMOR CACHAREL TESTER 3.4 EAU DE TOILETTE SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100006",
    //     img: test6,
    //     productName: "ANGEL TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    //     price: "39.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Isabella K",
    //     review: "Bold and sweet gourmand fragrance. Very strong projection and long-lasting performance.",
    //     des: "ANGEL TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100007",
    //     img: test7,
    //     productName: "ARIANA GRANDE ARI TESTER 3.4 EAU DE PARFUM SPRAY",
    //     price: "22.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Mia S",
    //     review: "Sweet and playful fragrance with a soft creamy finish. Great casual everyday scent.",
    //     des: "ARIANA GRANDE ARI TESTER 3.4 EAU DE PARFUM SPRAY",
    //   },
    //   {
    //     _id: "100008",
    //     img: test8,
    //     productName: "ARIANA GRANDE MOD BLUSH TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    //     price: "26.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Emma J",
    //     review: "Modern sweet floral scent with a smooth finish. Easy to wear and very feminine.",
    //     des: "ARIANA GRANDE MOD BLUSH TESTER 3.4 EAU DE PARFUM SPRAY FOR WOMEN",
    //   },
    //   {
    //     _id: "100009",
    //     img: test9,
    //     productName: "BONBON V&R UNBOXED 0.24 EAU DE PARFUM MINI FOR WOMEN",
    //     price: "14.99",
    //     Oz: "0.24",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Charlotte D",
    //     review: "Very sweet caramel-like fragrance in a compact size. Great for travel or purse carry.",
    //     des: "BONBON V&R UNBOXED 0.24 EAU DE PARFUM MINI FOR WOMEN",
    //   },
    //   {
    //     _id: "100010",
    //     img: test10,
    //     productName: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
    //     price: "18.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Lily H",
    //     review: "Light and fun fragrance designed for younger users. Soft and pleasant scent profile.",
    //     des: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
    //   },
    // ],
    // children: [
    //   {
    //     _id: "100001",
    //     img: ch1,
    //     productName: "DC COMICS CATWOMAN 3.4 EAU DE TOILETTE SPRAY",
    //     price: "6.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.4,
    //     reviewName: "Mia S",
    //     review: "Sweet playful scent with a light fruity touch. Kids love the fun character bottle design.",
    //     des: "DC COMICS CATWOMAN 3.4 EAU DE TOILETTE SPRAY",
    //   },
    //   {
    //     _id: "100002",
    //     img: ch2,
    //     productName: "DISNEY DAISY DUCK 3.4 EAU DE TOILETTE SPRAY",
    //     price: "7.49",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Emily W",
    //     review: "Soft floral fragrance with a very light sweet finish. Fun and kid-friendly scent.",
    //     des: "DISNEY DAISY DUCK 3.4 EAU DE TOILETTE SPRAY",
    //   },
    //   {
    //     _id: "100003",
    //     img: ch3,
    //     productName: "DISNEY DONALD DUCK 3.4 EAU DE TOILETTE SPRAY",
    //     price: "7.49",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.4,
    //     reviewName: "Liam K",
    //     review: "Fresh and light fragrance. Simple and safe scent for kids with a playful vibe.",
    //     des: "DISNEY DONALD DUCK 3.4 EAU DE TOILETTE SPRAY",
    //   },
    //   {
    //     _id: "100004",
    //     img: ch4,
    //     productName: "DISNEY ENCANTO 3.4 EAU DE TOILETTE SPRAY",
    //     price: "7.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.6,
    //     reviewName: "Olivia M",
    //     review: "Colorful and cheerful fragrance. Sweet light scent inspired by the movie theme.",
    //     des: "DISNEY ENCANTO 3.4 EAU DE TOILETTE SPRAY",
    //   },
    //   {
    //     _id: "100005",
    //     img: ch5,
    //     productName: "DISNEY FROZEN 2 3.4 EAU DE TOILETTE SPRAY WITH CHARM",
    //     price: "8.49",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.7,
    //     reviewName: "Ava L",
    //     review: "Fresh icy-sweet scent. Fun collectible bottle with charm makes it extra special.",
    //     des: "DISNEY FROZEN 2 3.4 EAU DE TOILETTE SPRAY WITH CHARM",
    //   },
    //   {
    //     _id: "100006",
    //     img: ch6,
    //     productName: "DISNEY FROZEN ANNA 3.4 EAU DE TOILETTE SPRAY",
    //     price: "7.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.6,
    //     reviewName: "Emma J",
    //     review: "Soft floral fruity fragrance. Very light and perfect for younger users.",
    //     des: "DISNEY FROZEN ANNA 3.4 EAU DE TOILETTE SPRAY",
    //   },
    //   {
    //     _id: "100007",
    //     img: ch7,
    //     productName: "DISNEY MICKEY MOUSE 3.4 EDT SP",
    //     price: "6.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.5,
    //     reviewName: "Noah P",
    //     review: "Simple clean scent with a playful character theme. Great everyday kids fragrance.",
    //     des: "DISNEY MICKEY MOUSE 3.4 EDT SP",
    //   },
    //   {
    //     _id: "100008",
    //     img: ch8,
    //     productName: "DISNEY PRINCESS ARIEL 3.4 EDT SP",
    //     price: "7.49",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.6,
    //     reviewName: "Sophia R",
    //     review: "Light oceanic floral scent. Sweet and soft fragrance for young users.",
    //     des: "DISNEY PRINCESS ARIEL 3.4 EDT SP",
    //   },
    //   {
    //     _id: "100009",
    //     img: ch9,
    //     productName: "DISNEY PRINCESS MOANA 3.4 EAU DE TOILETTE SPRAY",
    //     price: "7.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.6,
    //     reviewName: "Isabella K",
    //     review: "Tropical fruity scent with a fresh vibe. Fun and vibrant kids fragrance.",
    //     des: "DISNEY PRINCESS MOANA 3.4 EAU DE TOILETTE SPRAY",
    //   },
    //   {
    //     _id: "100010",
    //     img: ch10,
    //     productName: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
    //     price: "7.99",
    //     Oz: "3.4",
    //     badge: true,
    //     rating: 4.6,
    //     reviewName: "Charlotte D",
    //     review: "Soft sweet floral scent. Light, playful and perfect for kids collection.",
    //     des: "DISNEY PRINCESS RAPUNZEL 3.4 EAU DE TOILETTE SPRAY",
    //   },
    // ],
  };
  
  export default productsData;
  